# syntax=docker/dockerfile:1
FROM node:24.4.0-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@10.22.0 --activate

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y python3 make g++ git python3-pip pkg-config libsecret-1-dev && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm --filter=@hanzo/platform --filter=./app/platform install --frozen-lockfile


# Deploy only the platform app
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ENV NODE_ENV=production
RUN pnpm --filter=@hanzo/platform build
RUN pnpm --filter=./app/platform run build

RUN pnpm --filter=./app/platform --prod deploy --legacy /prod/platform

RUN cp -R /usr/src/app/app/platform/.next /prod/platform/.next
RUN cp -R /usr/src/app/app/platform/dist /prod/platform/dist

FROM base AS platform
WORKDIR /app

# Set production
ENV NODE_ENV=production

RUN apt-get update && apt-get install -y curl unzip apache2-utils && rm -rf /var/lib/apt/lists/*

# Copy only the necessary files
COPY --from=build /prod/platform/.next ./.next
COPY --from=build /prod/platform/dist ./dist
COPY --from=build /prod/platform/next.config.mjs ./next.config.mjs
COPY --from=build /prod/platform/public ./public
COPY --from=build /prod/platform/package.json ./package.json
COPY --from=build /prod/platform/drizzle ./drizzle
COPY --from=build /prod/platform/components.json ./components.json
COPY --from=build /prod/platform/node_modules ./node_modules


# Install RCLONE
RUN curl https://rclone.org/install.sh | bash

# tsx
RUN pnpm install -g tsx

EXPOSE 3000
CMD [ "pnpm", "start" ]
