# syntax=docker/dockerfile:1
FROM node:24.4.0-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@10.22.0 --activate

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y python3 make g++ git python3-pip pkg-config libsecret-1-dev && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm --filter=@hanzo/platform --filter=./app/schedules install --frozen-lockfile

# Deploy only the schedules app

ENV NODE_ENV=production
RUN pnpm --filter=@hanzo/platform build
RUN pnpm --filter=@hanzo/platform-server build
RUN pnpm --filter=./app/schedules run build

RUN pnpm --filter=./app/schedules --prod deploy --legacy /prod/schedules

RUN cp -R /usr/src/app/app/schedules/dist /prod/schedules/dist

FROM base AS schedules
WORKDIR /app

# Set production
ENV NODE_ENV=production

# Copy only the necessary files
COPY --from=build /prod/schedules/dist ./dist
COPY --from=build /prod/schedules/package.json ./package.json
COPY --from=build /prod/schedules/node_modules ./node_modules

ENV HOSTNAME=0.0.0.0
CMD ["pnpm", "start"]
