# syntax=docker/dockerfile:1
FROM node:20.16.0-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@9.12.0 --activate

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y python3 make g++ git python3-pip pkg-config libsecret-1-dev && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm --filter=@hanzo/core --filter=./app/hanzo install --frozen-lockfile


# Deploy only the hanzo app
ARG NEXT_PUBLIC_UMAMI_HOST
ENV NEXT_PUBLIC_UMAMI_HOST=$NEXT_PUBLIC_UMAMI_HOST

ARG NEXT_PUBLIC_UMAMI_WEBSITE_ID
ENV NEXT_PUBLIC_UMAMI_WEBSITE_ID=$NEXT_PUBLIC_UMAMI_WEBSITE_ID

ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ENV NODE_ENV=production
RUN pnpm --filter=@hanzo/core build
RUN pnpm --filter=./app/hanzo run build

RUN pnpm --filter=./app/hanzo --prod deploy /prod/hanzo

RUN cp -R /usr/src/app/app/hanzo/.next /prod/hanzo/.next
RUN cp -R /usr/src/app/app/hanzo/dist /prod/hanzo/dist

FROM base AS hanzo
WORKDIR /app

# Set production
ENV NODE_ENV=production

RUN apt-get update && apt-get install -y curl unzip apache2-utils && rm -rf /var/lib/apt/lists/*

# Copy only the necessary files
COPY --from=build /prod/hanzo/.next ./.next
COPY --from=build /prod/hanzo/dist ./dist
COPY --from=build /prod/hanzo/next.config.mjs ./next.config.mjs
COPY --from=build /prod/hanzo/public ./public
COPY --from=build /prod/hanzo/package.json ./package.json
COPY --from=build /prod/hanzo/drizzle ./drizzle
COPY --from=build /prod/hanzo/components.json ./components.json
COPY --from=build /prod/hanzo/node_modules ./node_modules


# Install RCLONE
RUN curl https://rclone.org/install.sh | bash

# tsx
RUN pnpm install -g tsx

EXPOSE 3000
CMD [ "pnpm", "start" ]