/**
 * One-click stack template registry.
 *
 * Ported from paas/platform/handlers/templates/index.js -- the canonical list
 * of database, cache, object-storage, and Hanzo service stacks that users can
 * deploy with a single click.
 */

import type { StackCategory } from "./types";

export const stackRegistry: StackCategory[] = [
	// -----------------------------------------------------------------
	// Databases
	// -----------------------------------------------------------------
	{
		category: "Database",
		templates: [
			{
				name: "MongoDB",
				description:
					"MongoDB is a general purpose, document-based database built for the cloud era.",
				manifest: "mongodbv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/docdb:latest",
						"networking.containerPort": 27017,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 512,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/data/db",
						"storageConfig.size": 1,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						username: "mongo-admin",
						password: "{{random:18}}",
						keyfile: "{{random:756}}",
					},
					variables: {
						MONGO_INITDB_ROOT_USERNAME: "{{secret:username}}",
						MONGO_INITDB_ROOT_PASSWORD: "{{secret:password}}",
						MONGO_INITDB_DATABASE: "admin",
					},
				},
			},
			{
				name: "PostgreSQL",
				description:
					"PostgreSQL is a powerful, open source object-relational database system.",
				manifest: "postgresqlv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/sql:18",
						"networking.containerPort": 5432,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 512,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/var/lib/postgresql/data",
						"storageConfig.size": 1,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						username: "postgres",
						password: "{{random:18}}",
					},
					variables: {
						POSTGRES_USER: "{{secret:username}}",
						POSTGRES_PASSWORD: "{{secret:password}}",
						PGDATA: "/var/lib/postgresql/dstore/data",
					},
				},
			},
			{
				name: "MySQL",
				description:
					"MySQL is an open-source relational database management system.",
				manifest: "mysqlv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/sql-mysql:8",
						"networking.containerPort": 3306,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 512,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/var/lib/mysql",
						"storageConfig.size": 1,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						username: "root",
						password: "{{random:18}}",
					},
					variables: {
						MYSQL_ROOT_USER: "{{secret:username}}",
						MYSQL_ROOT_PASSWORD: "{{secret:password}}",
					},
				},
			},
			{
				name: "MariaDB",
				description:
					"MariaDB is a community-developed, commercially supported fork of the MySQL relational database management system.",
				manifest: "mariadbv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/sql-maria:11",
						"networking.containerPort": 3306,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 512,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/var/lib/mysql",
						"storageConfig.size": 1,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						username: "root",
						password: "{{random:18}}",
					},
					variables: {
						MARIADB_ROOT_USER: "{{secret:username}}",
						MARIADB_ROOT_PASSWORD: "{{secret:password}}",
					},
				},
			},
		],
	},
	// -----------------------------------------------------------------
	// KV Stores
	// -----------------------------------------------------------------
	{
		category: "KV Store",
		templates: [
			{
				name: "Redis",
				description:
					"Redis is an open source in-memory data structure store, used as a database, cache and message broker.",
				manifest: "redisv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/kv:8",
						"networking.containerPort": 6379,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 256,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/data",
						"storageConfig.size": 512,
						"storageConfig.sizeType": "mebibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						password: "{{random:18}}",
					},
					variables: {
						REDIS_PASSWORD: "{{secret:password}}",
					},
				},
			},
			{
				name: "Memcached",
				description:
					"Memcached is a general-purpose distributed memory-caching system.",
				manifest: "memcachedv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "deployment",
				config: {
					visibleSections: ["general", "networking", "podConfig"],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
					],
					disabledFields: ["networking.containerPort"],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "docker.io/memcached:1.6.28",
						"networking.containerPort": 11211,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 256,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": false,
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
						"deploymentConfig.desiredReplicas": 1,
						"deploymentConfig.cpuMetric.enabled": false,
						"deploymentConfig.memoryMetric.enabled": false,
					},
					secrets: {},
					variables: {},
				},
			},
		],
	},
	// -----------------------------------------------------------------
	// Container Registry
	// -----------------------------------------------------------------
	{
		category: "Container Registry",
		templates: [
			{
				name: "Docker Registry",
				description:
					"In-cluster Docker registry v2 with htpasswd auth and persistent storage. Pushes/pulls from PaaS-built images stay inside the cluster.",
				manifest: "registryv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "docker.io/registry:2",
						"networking.containerPort": 5000,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 500,
						"podConfig.cpuLimitType": "millicores",
						"podConfig.memoryRequest": 128,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 512,
						"podConfig.memoryLimitType": "mebibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/var/lib/registry",
						"storageConfig.size": 10,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					// htpasswd is a bcrypt-hashed user:pass pair. Default user
					// "registry" / random 18-char password — operator can
					// override before deploy. Generated by the substitution
					// pre-pass via {{random:18}}.
					secrets: {
						htpasswd: "registry:{{random:18}}",
					},
					variables: {},
				},
			},
		],
	},
	// -----------------------------------------------------------------
	// Object Storage
	// -----------------------------------------------------------------
	{
		category: "Object Storage",
		templates: [
			{
				name: "S3 Object Storage",
				description:
					"High-performance, S3-compatible distributed object storage for large-scale cloud infrastructure.",
				manifest: "miniov1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl":
							"ghcr.io/hanzoai/storage:latest",
						"networking.containerPort": 9000,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 256,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/data",
						"storageConfig.size": 1,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						accessKey: "{{random:18}}",
						secretKey: "{{random:18}}",
					},
					variables: {
						MINIO_ROOT_USER: "{{secret:accessKey}}",
						MINIO_ROOT_PASSWORD: "{{secret:secretKey}}",
					},
				},
			},
		],
	},
	// -----------------------------------------------------------------
	// AI Agents
	// -----------------------------------------------------------------
	{
		category: "AI Agents",
		templates: [
			{
				name: "Hanzo Bot Runtime",
				description:
					"KMS-backed bot runtime with built-in access contract for Hanzo IAM, KV, and SQL services.",
				manifest: "hanzo-botv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "deployment",
				config: {
					visibleSections: ["general", "networking", "podConfig"],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
					],
					disabledFields: [],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/bot:latest",
						"networking.containerPort": 18789,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 256,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": false,
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
						"deploymentConfig.desiredReplicas": 1,
						"deploymentConfig.cpuMetric.enabled": false,
						"deploymentConfig.memoryMetric.enabled": false,
					},
					secrets: {},
					variables: {
						HANZO_BOT_TARGET_CLOUD: "hanzo-k8s",
						HANZO_BOT_TARGET_REGION: "do-sfo3",
						HANZO_BILLING_MODE: "prepaid",
						HANZO_PLATFORM_MARKUP_PERCENT: "25",
						HANZO_OSS_DEV_POOL_PERCENT: "25",
						HANZO_USAGE_METERING_BACKEND: "iam",
						HANZO_USAGE_ENDPOINT:
							"http://iam.hanzo.svc.cluster.local:8000/api/add-usage-record",
						HANZO_DEVICE_MESH_ENABLED: "true",
					},
				},
			},
		],
	},
	// -----------------------------------------------------------------
	// AI Workflows
	// -----------------------------------------------------------------
	{
		category: "AI Workflows",
		templates: [
			{
				name: "Hanzo Flow",
				description:
					"Visual AI workflow builder with drag-and-drop agent orchestration, LLM integration, and IAM SSO authentication.",
				manifest: "hanzo-flowv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "deployment",
				config: {
					visibleSections: ["general", "networking", "podConfig"],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
					],
					disabledFields: [],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/flow:latest",
						"networking.containerPort": 7860,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 200,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 1,
						"podConfig.cpuLimitType": "cores",
						"podConfig.memoryRequest": 512,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 2,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": false,
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
						"deploymentConfig.desiredReplicas": 1,
						"deploymentConfig.cpuMetric.enabled": false,
						"deploymentConfig.memoryMetric.enabled": false,
					},
					secrets: {},
					variables: {
						HANZO_FLOW_TARGET_CLOUD: "hanzo-k8s",
						HANZO_FLOW_TARGET_REGION: "do-sfo3",
						HANZO_BILLING_MODE: "prepaid",
						HANZO_PLATFORM_MARKUP_PERCENT: "20",
						HANZO_OSS_DEV_POOL_PERCENT: "25",
						HANZO_USAGE_METERING_BACKEND: "iam",
						HANZO_USAGE_ENDPOINT:
							"http://iam.hanzo.svc.cluster.local:8000/api/add-usage-record",
					},
				},
			},
		],
	},
	// -----------------------------------------------------------------
	// Hanzo Services
	// -----------------------------------------------------------------
	{
		category: "Hanzo Services",
		templates: [
			{
				name: "Hanzo Base",
				description:
					"Backend-as-a-service with embedded SQLite, REST/Realtime APIs, auth, file storage, and admin dashboard.",
				manifest: "hanzo-basev1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/base:latest",
						"networking.containerPort": 8090,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 500,
						"podConfig.cpuLimitType": "millicores",
						"podConfig.memoryRequest": 128,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 512,
						"podConfig.memoryLimitType": "mebibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/app/data",
						"storageConfig.size": 1,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						superuserEmail: "admin@hanzo.ai",
						superuserPassword: "{{random:24}}",
					},
					variables: {
						HANZO_BASE_TARGET_CLOUD: "hanzo-k8s",
						HANZO_BASE_TARGET_REGION: "do-sfo3",
						HANZO_BILLING_MODE: "prepaid",
						HANZO_USAGE_METERING_BACKEND: "iam",
					},
				},
			},
			{
				name: "Hanzo Base + Tasks",
				description:
					"Hanzo Base with Temporal-powered durable task execution sidecar for background jobs, scheduled workflows, and event-driven processing.",
				manifest: "hanzo-base-tasksv1.0.yaml",
				version: "1.0",
				isLatest: true,
				type: "statefulset",
				config: {
					visibleSections: [
						"general",
						"networking",
						"podConfig",
						"storageConfig",
					],
					visibleFields: [
						"name",
						"networking.containerPort",
						"networking.tcpProxy.enabled",
						"podConfig.cpuRequest",
						"podConfig.cpuRequestType",
						"podConfig.cpuLimit",
						"podConfig.cpuLimitType",
						"podConfig.memoryRequest",
						"podConfig.memoryRequestType",
						"podConfig.memoryLimit",
						"podConfig.memoryLimitType",
						"storageConfig.enabled",
						"storageConfig.size",
						"storageConfig.sizeType",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled",
					],
					disabledFields: [
						"networking.containerPort",
						"storageConfig.enabled",
					],
					defaultValues: {
						repoOrRegistry: "registry",
						"registry.imageUrl": "ghcr.io/hanzoai/base:latest",
						"networking.containerPort": 8090,
						"networking.tcpProxy.enabled": false,
						"podConfig.restartPolicy": "Always",
						"podConfig.cpuRequest": 100,
						"podConfig.cpuRequestType": "millicores",
						"podConfig.cpuLimit": 500,
						"podConfig.cpuLimitType": "millicores",
						"podConfig.memoryRequest": 256,
						"podConfig.memoryRequestType": "mebibyte",
						"podConfig.memoryLimit": 1,
						"podConfig.memoryLimitType": "gibibyte",
						"storageConfig.enabled": true,
						"storageConfig.mountPath": "/app/data",
						"storageConfig.size": 1,
						"storageConfig.sizeType": "gibibyte",
						"storageConfig.accessModes": ["ReadWriteOnce"],
						"statefulSetConfig.desiredReplicas": 1,
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenDeleted":
							"Retain",
						"statefulSetConfig.persistentVolumeClaimRetentionPolicy.whenScaled":
							"Retain",
						"probes.readiness.enabled": false,
						"probes.liveness.enabled": false,
						"probes.startup.enabled": false,
					},
					secrets: {
						superuserEmail: "admin@hanzo.ai",
						superuserPassword: "{{random:24}}",
					},
					variables: {
						HANZO_BASE_TARGET_CLOUD: "hanzo-k8s",
						HANZO_BASE_TARGET_REGION: "do-sfo3",
						HANZO_BILLING_MODE: "prepaid",
						HANZO_USAGE_METERING_BACKEND: "iam",
						HANZO_TASKS_ADDRESS: "tasks.hanzo.svc.cluster.local:7233",
						HANZO_TASKS_ENABLED: "true",
					},
				},
			},
		],
	},
];
