apiVersion: v1
kind: Secret
metadata:
  name: {{iid}}
  namespace: {{namespace}}
type: Opaque
stringData:
  username: {{secrets.username}}
  password: {{secrets.password}}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{iid}}
  namespace: {{namespace}}
spec:
  serviceName: {{iid}}
  replicas: 1
  updateStrategy:
    type: {{statefulSetConfig.strategy}}
    rollingUpdate:
      maxUnavailable: {{statefulSetConfig.rollingUpdate.maxUnavailable}}
      partition: {{statefulSetConfig.rollingUpdate.partition}}
  revisionHistoryLimit: {{statefulSetConfig.revisionHistoryLimit}}
  podManagementPolicy: {{statefulSetConfig.podManagementPolicy}}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app: {{iid}}
  template:
    metadata:
      labels:
        app: {{iid}}
    spec:
      containers:
      - name: datastore
        image: {{registry.imageUrl}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        - containerPort: 9000
          name: native
          protocol: TCP
        resources:
          requests:
            memory: {{podConfig.memoryRequest}}{{podConfig.memoryRequestType}}
            cpu: {{podConfig.cpuRequest}}{{podConfig.cpuRequestType}}
          limits:
            memory: {{podConfig.memoryLimit}}{{podConfig.memoryLimitType}}
            cpu: {{podConfig.cpuLimit}}{{podConfig.cpuLimitType}}
        env:
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: {{iid}}
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{iid}}
        - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          value: "1"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8123
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 6
        readinessProbe:
          httpGet:
            path: /ping
            port: 8123
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 6
        volumeMounts:
        - name: data
          mountPath: /var/lib/datastore
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{storageConfig.size}}{{storageConfig.sizeType}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{iid}}
  namespace: {{namespace}}
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: native
  selector:
    app: {{iid}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{iid}}-headless
  namespace: {{namespace}}
spec:
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: native
  clusterIP: None
  selector:
    app: {{iid}}
