apiVersion: v1
kind: Secret
metadata:
  name: {{iid}}
  namespace: {{namespace}}
type: Opaque
stringData:
  accessKey: {{secrets.accessKey}}
  secretKey: {{secrets.secretKey}}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{iid}}
  namespace: {{namespace}}
spec:
  serviceName: {{iid}}
  replicas: 1
  updateStrategy:
    type: {{statefulSetConfig.strategy}}
    rollingUpdate:
      maxUnavailable: {{statefulSetConfig.rollingUpdate.maxUnavailable}}
      partition: {{statefulSetConfig.rollingUpdate.partition}}
  revisionHistoryLimit: {{statefulSetConfig.revisionHistoryLimit}}
  podManagementPolicy: {{statefulSetConfig.podManagementPolicy}}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app: {{iid}}
  template:
    metadata:
      labels:
        app: {{iid}}
    spec:
      containers:
      - name: s3
        image: {{registry.imageUrl}}
        args:
        - server
        - -dir=/data
        - -ip.bind=0.0.0.0
        - -filer
        - -s3
        - -s3.port=9000
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: s3
          protocol: TCP
        resources:
          requests:
            memory: {{podConfig.memoryRequest}}{{podConfig.memoryRequestType}}
            cpu: {{podConfig.cpuRequest}}{{podConfig.cpuRequestType}}
          limits:
            memory: {{podConfig.memoryLimit}}{{podConfig.memoryLimitType}}
            cpu: {{podConfig.cpuLimit}}{{podConfig.cpuLimitType}}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accessKey
              name: {{iid}}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: {{iid}}
        readinessProbe:
          tcpSocket:
            port: 9000
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{storageConfig.size}}{{storageConfig.sizeType}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{iid}}
  namespace: {{namespace}}
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    name: s3
  selector:
    app: {{iid}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{iid}}-headless
  namespace: {{namespace}}
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: s3
  clusterIP: None
  selector:
    app: {{iid}}
