// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: admin.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Admin service (stable wire ids). */
export const AdminMethod = {
  setupMonitoring: 1,
} as const;

/** Typed RPC client for the Admin service over a ZAP call channel. */
export interface AdminChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class AdminClient {
  constructor(private readonly channel: AdminChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async setupMonitoring(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AdminMethod.setupMonitoring,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Admin.setupMonitoring: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Admin service. Subclass and implement each method. */
export abstract class AdminServer {
  abstract setupMonitoring(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case AdminMethod.setupMonitoring: {
        const body = await this.setupMonitoring(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


