// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: ai.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Ai service (stable wire ids). */
export const AiMethod = {
  one: 1,
  getModels: 2,
  create: 3,
  update: 4,
  getAll: 5,
  get: 6,
  delete: 7,
  getEnabledProviders: 8,
  analyzeLogs: 9,
  testConnection: 10,
  suggest: 11,
  deploy: 12,
} as const;

/** Typed RPC client for the Ai service over a ZAP call channel. */
export interface AiChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class AiClient {
  constructor(private readonly channel: AiChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async getModels(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.getModels,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.getModels: status ${resp.status}`);
    }
    return resp.body;
  }

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async getAll(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.getAll,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.getAll: status ${resp.status}`);
    }
    return resp.body;
  }

  async get(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.get,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.get: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async getEnabledProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.getEnabledProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.getEnabledProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async analyzeLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.analyzeLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.analyzeLogs: status ${resp.status}`);
    }
    return resp.body;
  }

  async testConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.testConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.testConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async suggest(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.suggest,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.suggest: status ${resp.status}`);
    }
    return resp.body;
  }

  async deploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AiMethod.deploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Ai.deploy: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Ai service. Subclass and implement each method. */
export abstract class AiServer {
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract getModels(args: Uint8Array): Promise<Uint8Array>;
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract getAll(args: Uint8Array): Promise<Uint8Array>;
  abstract get(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract getEnabledProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract analyzeLogs(args: Uint8Array): Promise<Uint8Array>;
  abstract testConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract suggest(args: Uint8Array): Promise<Uint8Array>;
  abstract deploy(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case AiMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.getModels: {
        const body = await this.getModels(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.getAll: {
        const body = await this.getAll(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.get: {
        const body = await this.get(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.getEnabledProviders: {
        const body = await this.getEnabledProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.analyzeLogs: {
        const body = await this.analyzeLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.testConnection: {
        const body = await this.testConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.suggest: {
        const body = await this.suggest(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case AiMethod.deploy: {
        const body = await this.deploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


