// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: application.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Application service (stable wire ids). */
export const ApplicationMethod = {
  create: 1,
  one: 2,
  reload: 3,
  delete: 4,
  stop: 5,
  start: 6,
  redeploy: 7,
  saveEnvironment: 8,
  saveBuildType: 9,
  saveGithubProvider: 10,
  saveGitlabProvider: 11,
  saveBitbucketProvider: 12,
  saveGiteaProvider: 13,
  saveDockerProvider: 14,
  saveGitProvider: 15,
  disconnectGitProvider: 16,
  markRunning: 17,
  update: 18,
  refreshToken: 19,
  deploy: 20,
  cleanQueues: 21,
  clearDeployments: 22,
  killBuild: 23,
  readTraefikConfig: 24,
  dropDeployment: 25,
  updateTraefikConfig: 26,
  readAppMonitoring: 27,
  move: 28,
  cancelDeployment: 29,
  search: 30,
  readLogs: 31,
} as const;

/** Typed RPC client for the Application service over a ZAP call channel. */
export interface ApplicationChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class ApplicationClient {
  constructor(private readonly channel: ApplicationChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async reload(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.reload,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.reload: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async stop(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.stop,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.stop: status ${resp.status}`);
    }
    return resp.body;
  }

  async start(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.start,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.start: status ${resp.status}`);
    }
    return resp.body;
  }

  async redeploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.redeploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.redeploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveEnvironment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveEnvironment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveEnvironment: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveBuildType(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveBuildType,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveBuildType: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveGithubProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveGithubProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveGithubProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveGitlabProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveGitlabProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveGitlabProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveBitbucketProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveBitbucketProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveBitbucketProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveGiteaProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveGiteaProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveGiteaProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveDockerProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveDockerProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveDockerProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveGitProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.saveGitProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.saveGitProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async disconnectGitProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.disconnectGitProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.disconnectGitProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async markRunning(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.markRunning,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.markRunning: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async refreshToken(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.refreshToken,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.refreshToken: status ${resp.status}`);
    }
    return resp.body;
  }

  async deploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.deploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.deploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanQueues(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.cleanQueues,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.cleanQueues: status ${resp.status}`);
    }
    return resp.body;
  }

  async clearDeployments(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.clearDeployments,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.clearDeployments: status ${resp.status}`);
    }
    return resp.body;
  }

  async killBuild(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.killBuild,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.killBuild: status ${resp.status}`);
    }
    return resp.body;
  }

  async readTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.readTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.readTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async dropDeployment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.dropDeployment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.dropDeployment: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.updateTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.updateTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async readAppMonitoring(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.readAppMonitoring,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.readAppMonitoring: status ${resp.status}`);
    }
    return resp.body;
  }

  async move(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.move,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.move: status ${resp.status}`);
    }
    return resp.body;
  }

  async cancelDeployment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.cancelDeployment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.cancelDeployment: status ${resp.status}`);
    }
    return resp.body;
  }

  async search(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.search,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.search: status ${resp.status}`);
    }
    return resp.body;
  }

  async readLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ApplicationMethod.readLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Application.readLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Application service. Subclass and implement each method. */
export abstract class ApplicationServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract reload(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract stop(args: Uint8Array): Promise<Uint8Array>;
  abstract start(args: Uint8Array): Promise<Uint8Array>;
  abstract redeploy(args: Uint8Array): Promise<Uint8Array>;
  abstract saveEnvironment(args: Uint8Array): Promise<Uint8Array>;
  abstract saveBuildType(args: Uint8Array): Promise<Uint8Array>;
  abstract saveGithubProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract saveGitlabProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract saveBitbucketProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract saveGiteaProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract saveDockerProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract saveGitProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract disconnectGitProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract markRunning(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract refreshToken(args: Uint8Array): Promise<Uint8Array>;
  abstract deploy(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanQueues(args: Uint8Array): Promise<Uint8Array>;
  abstract clearDeployments(args: Uint8Array): Promise<Uint8Array>;
  abstract killBuild(args: Uint8Array): Promise<Uint8Array>;
  abstract readTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract dropDeployment(args: Uint8Array): Promise<Uint8Array>;
  abstract updateTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract readAppMonitoring(args: Uint8Array): Promise<Uint8Array>;
  abstract move(args: Uint8Array): Promise<Uint8Array>;
  abstract cancelDeployment(args: Uint8Array): Promise<Uint8Array>;
  abstract search(args: Uint8Array): Promise<Uint8Array>;
  abstract readLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case ApplicationMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.reload: {
        const body = await this.reload(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.stop: {
        const body = await this.stop(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.start: {
        const body = await this.start(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.redeploy: {
        const body = await this.redeploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveEnvironment: {
        const body = await this.saveEnvironment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveBuildType: {
        const body = await this.saveBuildType(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveGithubProvider: {
        const body = await this.saveGithubProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveGitlabProvider: {
        const body = await this.saveGitlabProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveBitbucketProvider: {
        const body = await this.saveBitbucketProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveGiteaProvider: {
        const body = await this.saveGiteaProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveDockerProvider: {
        const body = await this.saveDockerProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.saveGitProvider: {
        const body = await this.saveGitProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.disconnectGitProvider: {
        const body = await this.disconnectGitProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.markRunning: {
        const body = await this.markRunning(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.refreshToken: {
        const body = await this.refreshToken(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.deploy: {
        const body = await this.deploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.cleanQueues: {
        const body = await this.cleanQueues(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.clearDeployments: {
        const body = await this.clearDeployments(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.killBuild: {
        const body = await this.killBuild(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.readTraefikConfig: {
        const body = await this.readTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.dropDeployment: {
        const body = await this.dropDeployment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.updateTraefikConfig: {
        const body = await this.updateTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.readAppMonitoring: {
        const body = await this.readAppMonitoring(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.move: {
        const body = await this.move(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.cancelDeployment: {
        const body = await this.cancelDeployment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.search: {
        const body = await this.search(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ApplicationMethod.readLogs: {
        const body = await this.readLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


