// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: args.zap

import {
  Builder,
  Message,
  StructView,
} from "@zap-proto/zap";

const argsStructOff = {
  json: 0,
} as const;
const argsStructSize = 8;

/** Zero-copy view into a ZAP-encoded ArgsStruct message. */
export class ArgsStruct extends StructView {
  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */
  static wrap(b: Uint8Array): ArgsStruct {
    const root = Message.parse(b).root();
    return new ArgsStruct(root.data, root.offset);
  }

  get json(): string { return this.text(argsStructOff.json); }
}

/** Field values for newArgsStruct. */
export interface ArgsStructInput {
  json: string;
}

/** Build a ZAP-encoded ArgsStruct message from `in` and return the bytes. */
export function newArgsStruct(in_: ArgsStructInput): Uint8Array {
  const b = new Builder(256);
  const ob = b.startObject(argsStructSize);
  ob.setText(argsStructOff.json, in_.json);
  ob.finishAsRoot();
  return b.finish();
}


