// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: audit-log.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the AuditLog service (stable wire ids). */
export const AuditLogMethod = {
  all: 1,
} as const;

/** Typed RPC client for the AuditLog service over a ZAP call channel. */
export interface AuditLogChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class AuditLogClient {
  constructor(private readonly channel: AuditLogChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: AuditLogMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`AuditLog.all: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the AuditLog service. Subclass and implement each method. */
export abstract class AuditLogServer {
  abstract all(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case AuditLogMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


