// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: backup.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Backup service (stable wire ids). */
export const BackupMethod = {
  create: 1,
  one: 2,
  update: 3,
  remove: 4,
  manualBackupPostgres: 5,
  manualBackupMySql: 6,
  manualBackupMariadb: 7,
  manualBackupCompose: 8,
  manualBackupMongo: 9,
  manualBackupLibsql: 10,
  listBackupFiles: 11,
  restoreBackupWithLogs: 12,
} as const;

/** Typed RPC client for the Backup service over a ZAP call channel. */
export interface BackupChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class BackupClient {
  constructor(private readonly channel: BackupChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async manualBackupPostgres(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.manualBackupPostgres,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.manualBackupPostgres: status ${resp.status}`);
    }
    return resp.body;
  }

  async manualBackupMySql(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.manualBackupMySql,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.manualBackupMySql: status ${resp.status}`);
    }
    return resp.body;
  }

  async manualBackupMariadb(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.manualBackupMariadb,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.manualBackupMariadb: status ${resp.status}`);
    }
    return resp.body;
  }

  async manualBackupCompose(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.manualBackupCompose,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.manualBackupCompose: status ${resp.status}`);
    }
    return resp.body;
  }

  async manualBackupMongo(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.manualBackupMongo,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.manualBackupMongo: status ${resp.status}`);
    }
    return resp.body;
  }

  async manualBackupLibsql(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.manualBackupLibsql,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.manualBackupLibsql: status ${resp.status}`);
    }
    return resp.body;
  }

  async listBackupFiles(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.listBackupFiles,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.listBackupFiles: status ${resp.status}`);
    }
    return resp.body;
  }

  async restoreBackupWithLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BackupMethod.restoreBackupWithLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Backup.restoreBackupWithLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Backup service. Subclass and implement each method. */
export abstract class BackupServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract manualBackupPostgres(args: Uint8Array): Promise<Uint8Array>;
  abstract manualBackupMySql(args: Uint8Array): Promise<Uint8Array>;
  abstract manualBackupMariadb(args: Uint8Array): Promise<Uint8Array>;
  abstract manualBackupCompose(args: Uint8Array): Promise<Uint8Array>;
  abstract manualBackupMongo(args: Uint8Array): Promise<Uint8Array>;
  abstract manualBackupLibsql(args: Uint8Array): Promise<Uint8Array>;
  abstract listBackupFiles(args: Uint8Array): Promise<Uint8Array>;
  abstract restoreBackupWithLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case BackupMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.manualBackupPostgres: {
        const body = await this.manualBackupPostgres(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.manualBackupMySql: {
        const body = await this.manualBackupMySql(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.manualBackupMariadb: {
        const body = await this.manualBackupMariadb(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.manualBackupCompose: {
        const body = await this.manualBackupCompose(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.manualBackupMongo: {
        const body = await this.manualBackupMongo(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.manualBackupLibsql: {
        const body = await this.manualBackupLibsql(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.listBackupFiles: {
        const body = await this.listBackupFiles(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BackupMethod.restoreBackupWithLogs: {
        const body = await this.restoreBackupWithLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


