// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: billing.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Billing service (stable wire ids). */
export const BillingMethod = {
  getWallet: 1,
  getBalance: 2,
  createSubscription: 3,
  addCredits: 4,
  getPlans: 5,
  createPortalSession: 6,
} as const;

/** Typed RPC client for the Billing service over a ZAP call channel. */
export interface BillingChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class BillingClient {
  constructor(private readonly channel: BillingChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async getWallet(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BillingMethod.getWallet,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Billing.getWallet: status ${resp.status}`);
    }
    return resp.body;
  }

  async getBalance(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BillingMethod.getBalance,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Billing.getBalance: status ${resp.status}`);
    }
    return resp.body;
  }

  async createSubscription(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BillingMethod.createSubscription,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Billing.createSubscription: status ${resp.status}`);
    }
    return resp.body;
  }

  async addCredits(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BillingMethod.addCredits,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Billing.addCredits: status ${resp.status}`);
    }
    return resp.body;
  }

  async getPlans(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BillingMethod.getPlans,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Billing.getPlans: status ${resp.status}`);
    }
    return resp.body;
  }

  async createPortalSession(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BillingMethod.createPortalSession,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Billing.createPortalSession: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Billing service. Subclass and implement each method. */
export abstract class BillingServer {
  abstract getWallet(args: Uint8Array): Promise<Uint8Array>;
  abstract getBalance(args: Uint8Array): Promise<Uint8Array>;
  abstract createSubscription(args: Uint8Array): Promise<Uint8Array>;
  abstract addCredits(args: Uint8Array): Promise<Uint8Array>;
  abstract getPlans(args: Uint8Array): Promise<Uint8Array>;
  abstract createPortalSession(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case BillingMethod.getWallet: {
        const body = await this.getWallet(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BillingMethod.getBalance: {
        const body = await this.getBalance(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BillingMethod.createSubscription: {
        const body = await this.createSubscription(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BillingMethod.addCredits: {
        const body = await this.addCredits(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BillingMethod.getPlans: {
        const body = await this.getPlans(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BillingMethod.createPortalSession: {
        const body = await this.createPortalSession(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


