// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: bitbucket.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Bitbucket service (stable wire ids). */
export const BitbucketMethod = {
  create: 1,
  one: 2,
  bitbucketProviders: 3,
  getBitbucketRepositories: 4,
  getBitbucketBranches: 5,
  testConnection: 6,
  update: 7,
} as const;

/** Typed RPC client for the Bitbucket service over a ZAP call channel. */
export interface BitbucketChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class BitbucketClient {
  constructor(private readonly channel: BitbucketChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BitbucketMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Bitbucket.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BitbucketMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Bitbucket.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async bitbucketProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BitbucketMethod.bitbucketProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Bitbucket.bitbucketProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async getBitbucketRepositories(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BitbucketMethod.getBitbucketRepositories,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Bitbucket.getBitbucketRepositories: status ${resp.status}`);
    }
    return resp.body;
  }

  async getBitbucketBranches(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BitbucketMethod.getBitbucketBranches,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Bitbucket.getBitbucketBranches: status ${resp.status}`);
    }
    return resp.body;
  }

  async testConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BitbucketMethod.testConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Bitbucket.testConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: BitbucketMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Bitbucket.update: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Bitbucket service. Subclass and implement each method. */
export abstract class BitbucketServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract bitbucketProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract getBitbucketRepositories(args: Uint8Array): Promise<Uint8Array>;
  abstract getBitbucketBranches(args: Uint8Array): Promise<Uint8Array>;
  abstract testConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case BitbucketMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BitbucketMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BitbucketMethod.bitbucketProviders: {
        const body = await this.bitbucketProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BitbucketMethod.getBitbucketRepositories: {
        const body = await this.getBitbucketRepositories(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BitbucketMethod.getBitbucketBranches: {
        const body = await this.getBitbucketBranches(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BitbucketMethod.testConnection: {
        const body = await this.testConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case BitbucketMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


