// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: cluster.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Cluster service (stable wire ids). */
export const ClusterMethod = {
  getNodes: 1,
  removeWorker: 2,
  addWorker: 3,
  addManager: 4,
} as const;

/** Typed RPC client for the Cluster service over a ZAP call channel. */
export interface ClusterChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class ClusterClient {
  constructor(private readonly channel: ClusterChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async getNodes(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ClusterMethod.getNodes,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Cluster.getNodes: status ${resp.status}`);
    }
    return resp.body;
  }

  async removeWorker(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ClusterMethod.removeWorker,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Cluster.removeWorker: status ${resp.status}`);
    }
    return resp.body;
  }

  async addWorker(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ClusterMethod.addWorker,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Cluster.addWorker: status ${resp.status}`);
    }
    return resp.body;
  }

  async addManager(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ClusterMethod.addManager,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Cluster.addManager: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Cluster service. Subclass and implement each method. */
export abstract class ClusterServer {
  abstract getNodes(args: Uint8Array): Promise<Uint8Array>;
  abstract removeWorker(args: Uint8Array): Promise<Uint8Array>;
  abstract addWorker(args: Uint8Array): Promise<Uint8Array>;
  abstract addManager(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case ClusterMethod.getNodes: {
        const body = await this.getNodes(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ClusterMethod.removeWorker: {
        const body = await this.removeWorker(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ClusterMethod.addWorker: {
        const body = await this.addWorker(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ClusterMethod.addManager: {
        const body = await this.addManager(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


