// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: compose.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Compose service (stable wire ids). */
export const ComposeMethod = {
  create: 1,
  one: 2,
  update: 3,
  saveEnvironment: 4,
  delete: 5,
  cleanQueues: 6,
  clearDeployments: 7,
  killBuild: 8,
  loadServices: 9,
  loadMountsByService: 10,
  fetchSourceType: 11,
  randomizeCompose: 12,
  isolatedDeployment: 13,
  getConvertedCompose: 14,
  deploy: 15,
  redeploy: 16,
  stop: 17,
  start: 18,
  getDefaultCommand: 19,
  refreshToken: 20,
  deployTemplate: 21,
  templates: 22,
  getTags: 23,
  disconnectGitProvider: 24,
  move: 25,
  processTemplate: 26,
  previewTemplate: 27,
  import: 28,
  cancelDeployment: 29,
  search: 30,
  readLogs: 31,
} as const;

/** Typed RPC client for the Compose service over a ZAP call channel. */
export interface ComposeChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class ComposeClient {
  constructor(private readonly channel: ComposeChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveEnvironment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.saveEnvironment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.saveEnvironment: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanQueues(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.cleanQueues,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.cleanQueues: status ${resp.status}`);
    }
    return resp.body;
  }

  async clearDeployments(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.clearDeployments,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.clearDeployments: status ${resp.status}`);
    }
    return resp.body;
  }

  async killBuild(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.killBuild,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.killBuild: status ${resp.status}`);
    }
    return resp.body;
  }

  async loadServices(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.loadServices,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.loadServices: status ${resp.status}`);
    }
    return resp.body;
  }

  async loadMountsByService(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.loadMountsByService,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.loadMountsByService: status ${resp.status}`);
    }
    return resp.body;
  }

  async fetchSourceType(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.fetchSourceType,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.fetchSourceType: status ${resp.status}`);
    }
    return resp.body;
  }

  async randomizeCompose(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.randomizeCompose,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.randomizeCompose: status ${resp.status}`);
    }
    return resp.body;
  }

  async isolatedDeployment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.isolatedDeployment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.isolatedDeployment: status ${resp.status}`);
    }
    return resp.body;
  }

  async getConvertedCompose(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.getConvertedCompose,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.getConvertedCompose: status ${resp.status}`);
    }
    return resp.body;
  }

  async deploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.deploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.deploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async redeploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.redeploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.redeploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async stop(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.stop,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.stop: status ${resp.status}`);
    }
    return resp.body;
  }

  async start(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.start,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.start: status ${resp.status}`);
    }
    return resp.body;
  }

  async getDefaultCommand(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.getDefaultCommand,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.getDefaultCommand: status ${resp.status}`);
    }
    return resp.body;
  }

  async refreshToken(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.refreshToken,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.refreshToken: status ${resp.status}`);
    }
    return resp.body;
  }

  async deployTemplate(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.deployTemplate,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.deployTemplate: status ${resp.status}`);
    }
    return resp.body;
  }

  async templates(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.templates,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.templates: status ${resp.status}`);
    }
    return resp.body;
  }

  async getTags(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.getTags,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.getTags: status ${resp.status}`);
    }
    return resp.body;
  }

  async disconnectGitProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.disconnectGitProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.disconnectGitProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async move(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.move,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.move: status ${resp.status}`);
    }
    return resp.body;
  }

  async processTemplate(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.processTemplate,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.processTemplate: status ${resp.status}`);
    }
    return resp.body;
  }

  async previewTemplate(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.previewTemplate,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.previewTemplate: status ${resp.status}`);
    }
    return resp.body;
  }

  async import(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.import,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.import: status ${resp.status}`);
    }
    return resp.body;
  }

  async cancelDeployment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.cancelDeployment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.cancelDeployment: status ${resp.status}`);
    }
    return resp.body;
  }

  async search(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.search,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.search: status ${resp.status}`);
    }
    return resp.body;
  }

  async readLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ComposeMethod.readLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Compose.readLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Compose service. Subclass and implement each method. */
export abstract class ComposeServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract saveEnvironment(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanQueues(args: Uint8Array): Promise<Uint8Array>;
  abstract clearDeployments(args: Uint8Array): Promise<Uint8Array>;
  abstract killBuild(args: Uint8Array): Promise<Uint8Array>;
  abstract loadServices(args: Uint8Array): Promise<Uint8Array>;
  abstract loadMountsByService(args: Uint8Array): Promise<Uint8Array>;
  abstract fetchSourceType(args: Uint8Array): Promise<Uint8Array>;
  abstract randomizeCompose(args: Uint8Array): Promise<Uint8Array>;
  abstract isolatedDeployment(args: Uint8Array): Promise<Uint8Array>;
  abstract getConvertedCompose(args: Uint8Array): Promise<Uint8Array>;
  abstract deploy(args: Uint8Array): Promise<Uint8Array>;
  abstract redeploy(args: Uint8Array): Promise<Uint8Array>;
  abstract stop(args: Uint8Array): Promise<Uint8Array>;
  abstract start(args: Uint8Array): Promise<Uint8Array>;
  abstract getDefaultCommand(args: Uint8Array): Promise<Uint8Array>;
  abstract refreshToken(args: Uint8Array): Promise<Uint8Array>;
  abstract deployTemplate(args: Uint8Array): Promise<Uint8Array>;
  abstract templates(args: Uint8Array): Promise<Uint8Array>;
  abstract getTags(args: Uint8Array): Promise<Uint8Array>;
  abstract disconnectGitProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract move(args: Uint8Array): Promise<Uint8Array>;
  abstract processTemplate(args: Uint8Array): Promise<Uint8Array>;
  abstract previewTemplate(args: Uint8Array): Promise<Uint8Array>;
  abstract import(args: Uint8Array): Promise<Uint8Array>;
  abstract cancelDeployment(args: Uint8Array): Promise<Uint8Array>;
  abstract search(args: Uint8Array): Promise<Uint8Array>;
  abstract readLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case ComposeMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.saveEnvironment: {
        const body = await this.saveEnvironment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.cleanQueues: {
        const body = await this.cleanQueues(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.clearDeployments: {
        const body = await this.clearDeployments(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.killBuild: {
        const body = await this.killBuild(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.loadServices: {
        const body = await this.loadServices(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.loadMountsByService: {
        const body = await this.loadMountsByService(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.fetchSourceType: {
        const body = await this.fetchSourceType(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.randomizeCompose: {
        const body = await this.randomizeCompose(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.isolatedDeployment: {
        const body = await this.isolatedDeployment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.getConvertedCompose: {
        const body = await this.getConvertedCompose(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.deploy: {
        const body = await this.deploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.redeploy: {
        const body = await this.redeploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.stop: {
        const body = await this.stop(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.start: {
        const body = await this.start(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.getDefaultCommand: {
        const body = await this.getDefaultCommand(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.refreshToken: {
        const body = await this.refreshToken(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.deployTemplate: {
        const body = await this.deployTemplate(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.templates: {
        const body = await this.templates(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.getTags: {
        const body = await this.getTags(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.disconnectGitProvider: {
        const body = await this.disconnectGitProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.move: {
        const body = await this.move(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.processTemplate: {
        const body = await this.processTemplate(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.previewTemplate: {
        const body = await this.previewTemplate(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.import: {
        const body = await this.import(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.cancelDeployment: {
        const body = await this.cancelDeployment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.search: {
        const body = await this.search(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ComposeMethod.readLogs: {
        const body = await this.readLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


