// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: custom-role.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the CustomRole service (stable wire ids). */
export const CustomRoleMethod = {
  all: 1,
  create: 2,
  update: 3,
  remove: 4,
  membersByRole: 5,
  getStatements: 6,
} as const;

/** Typed RPC client for the CustomRole service over a ZAP call channel. */
export interface CustomRoleChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class CustomRoleClient {
  constructor(private readonly channel: CustomRoleChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: CustomRoleMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`CustomRole.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: CustomRoleMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`CustomRole.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: CustomRoleMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`CustomRole.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: CustomRoleMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`CustomRole.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async membersByRole(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: CustomRoleMethod.membersByRole,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`CustomRole.membersByRole: status ${resp.status}`);
    }
    return resp.body;
  }

  async getStatements(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: CustomRoleMethod.getStatements,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`CustomRole.getStatements: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the CustomRole service. Subclass and implement each method. */
export abstract class CustomRoleServer {
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract membersByRole(args: Uint8Array): Promise<Uint8Array>;
  abstract getStatements(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case CustomRoleMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case CustomRoleMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case CustomRoleMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case CustomRoleMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case CustomRoleMethod.membersByRole: {
        const body = await this.membersByRole(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case CustomRoleMethod.getStatements: {
        const body = await this.getStatements(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


