// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: deployment.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Deployment service (stable wire ids). */
export const DeploymentMethod = {
  all: 1,
  allByCompose: 2,
  allByServer: 3,
  allCentralized: 4,
  queueList: 5,
  allByType: 6,
  killProcess: 7,
  removeDeployment: 8,
  readLogs: 9,
} as const;

/** Typed RPC client for the Deployment service over a ZAP call channel. */
export interface DeploymentChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class DeploymentClient {
  constructor(private readonly channel: DeploymentChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async allByCompose(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.allByCompose,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.allByCompose: status ${resp.status}`);
    }
    return resp.body;
  }

  async allByServer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.allByServer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.allByServer: status ${resp.status}`);
    }
    return resp.body;
  }

  async allCentralized(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.allCentralized,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.allCentralized: status ${resp.status}`);
    }
    return resp.body;
  }

  async queueList(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.queueList,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.queueList: status ${resp.status}`);
    }
    return resp.body;
  }

  async allByType(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.allByType,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.allByType: status ${resp.status}`);
    }
    return resp.body;
  }

  async killProcess(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.killProcess,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.killProcess: status ${resp.status}`);
    }
    return resp.body;
  }

  async removeDeployment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.removeDeployment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.removeDeployment: status ${resp.status}`);
    }
    return resp.body;
  }

  async readLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DeploymentMethod.readLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Deployment.readLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Deployment service. Subclass and implement each method. */
export abstract class DeploymentServer {
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract allByCompose(args: Uint8Array): Promise<Uint8Array>;
  abstract allByServer(args: Uint8Array): Promise<Uint8Array>;
  abstract allCentralized(args: Uint8Array): Promise<Uint8Array>;
  abstract queueList(args: Uint8Array): Promise<Uint8Array>;
  abstract allByType(args: Uint8Array): Promise<Uint8Array>;
  abstract killProcess(args: Uint8Array): Promise<Uint8Array>;
  abstract removeDeployment(args: Uint8Array): Promise<Uint8Array>;
  abstract readLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case DeploymentMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.allByCompose: {
        const body = await this.allByCompose(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.allByServer: {
        const body = await this.allByServer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.allCentralized: {
        const body = await this.allCentralized(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.queueList: {
        const body = await this.queueList(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.allByType: {
        const body = await this.allByType(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.killProcess: {
        const body = await this.killProcess(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.removeDeployment: {
        const body = await this.removeDeployment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DeploymentMethod.readLogs: {
        const body = await this.readLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


