// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: digitalocean.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the DigitalOcean service (stable wire ids). */
export const DigitalOceanMethod = {
  configureProvider: 1,
  updateProvider: 2,
  listProviders: 3,
  getProvider: 4,
  deleteProvider: 5,
  listSizes: 6,
  listRegions: 7,
  scaleUp: 8,
  scaleDown: 9,
  resizeInstance: 10,
  drainNode: 11,
  removeInstance: 12,
  listPoolInstances: 13,
  getScalingStatus: 14,
  listScalingJobs: 15,
  createFirewall: 16,
  createLoadBalancer: 17,
  registerNode: 18,
  getSwarmJoinToken: 19,
} as const;

/** Typed RPC client for the DigitalOcean service over a ZAP call channel. */
export interface DigitalOceanChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class DigitalOceanClient {
  constructor(private readonly channel: DigitalOceanChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async configureProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.configureProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.configureProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.updateProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.updateProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async listProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.listProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.listProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async getProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.getProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.getProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.deleteProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.deleteProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async listSizes(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.listSizes,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.listSizes: status ${resp.status}`);
    }
    return resp.body;
  }

  async listRegions(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.listRegions,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.listRegions: status ${resp.status}`);
    }
    return resp.body;
  }

  async scaleUp(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.scaleUp,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.scaleUp: status ${resp.status}`);
    }
    return resp.body;
  }

  async scaleDown(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.scaleDown,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.scaleDown: status ${resp.status}`);
    }
    return resp.body;
  }

  async resizeInstance(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.resizeInstance,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.resizeInstance: status ${resp.status}`);
    }
    return resp.body;
  }

  async drainNode(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.drainNode,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.drainNode: status ${resp.status}`);
    }
    return resp.body;
  }

  async removeInstance(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.removeInstance,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.removeInstance: status ${resp.status}`);
    }
    return resp.body;
  }

  async listPoolInstances(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.listPoolInstances,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.listPoolInstances: status ${resp.status}`);
    }
    return resp.body;
  }

  async getScalingStatus(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.getScalingStatus,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.getScalingStatus: status ${resp.status}`);
    }
    return resp.body;
  }

  async listScalingJobs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.listScalingJobs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.listScalingJobs: status ${resp.status}`);
    }
    return resp.body;
  }

  async createFirewall(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.createFirewall,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.createFirewall: status ${resp.status}`);
    }
    return resp.body;
  }

  async createLoadBalancer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.createLoadBalancer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.createLoadBalancer: status ${resp.status}`);
    }
    return resp.body;
  }

  async registerNode(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.registerNode,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.registerNode: status ${resp.status}`);
    }
    return resp.body;
  }

  async getSwarmJoinToken(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DigitalOceanMethod.getSwarmJoinToken,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`DigitalOcean.getSwarmJoinToken: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the DigitalOcean service. Subclass and implement each method. */
export abstract class DigitalOceanServer {
  abstract configureProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract updateProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract listProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract getProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract deleteProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract listSizes(args: Uint8Array): Promise<Uint8Array>;
  abstract listRegions(args: Uint8Array): Promise<Uint8Array>;
  abstract scaleUp(args: Uint8Array): Promise<Uint8Array>;
  abstract scaleDown(args: Uint8Array): Promise<Uint8Array>;
  abstract resizeInstance(args: Uint8Array): Promise<Uint8Array>;
  abstract drainNode(args: Uint8Array): Promise<Uint8Array>;
  abstract removeInstance(args: Uint8Array): Promise<Uint8Array>;
  abstract listPoolInstances(args: Uint8Array): Promise<Uint8Array>;
  abstract getScalingStatus(args: Uint8Array): Promise<Uint8Array>;
  abstract listScalingJobs(args: Uint8Array): Promise<Uint8Array>;
  abstract createFirewall(args: Uint8Array): Promise<Uint8Array>;
  abstract createLoadBalancer(args: Uint8Array): Promise<Uint8Array>;
  abstract registerNode(args: Uint8Array): Promise<Uint8Array>;
  abstract getSwarmJoinToken(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case DigitalOceanMethod.configureProvider: {
        const body = await this.configureProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.updateProvider: {
        const body = await this.updateProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.listProviders: {
        const body = await this.listProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.getProvider: {
        const body = await this.getProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.deleteProvider: {
        const body = await this.deleteProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.listSizes: {
        const body = await this.listSizes(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.listRegions: {
        const body = await this.listRegions(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.scaleUp: {
        const body = await this.scaleUp(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.scaleDown: {
        const body = await this.scaleDown(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.resizeInstance: {
        const body = await this.resizeInstance(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.drainNode: {
        const body = await this.drainNode(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.removeInstance: {
        const body = await this.removeInstance(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.listPoolInstances: {
        const body = await this.listPoolInstances(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.getScalingStatus: {
        const body = await this.getScalingStatus(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.listScalingJobs: {
        const body = await this.listScalingJobs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.createFirewall: {
        const body = await this.createFirewall(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.createLoadBalancer: {
        const body = await this.createLoadBalancer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.registerNode: {
        const body = await this.registerNode(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DigitalOceanMethod.getSwarmJoinToken: {
        const body = await this.getSwarmJoinToken(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


