// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: dns.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Dns service (stable wire ids). */
export const DnsMethod = {
  listZones: 1,
  createZone: 2,
  deleteZone: 3,
  listRecords: 4,
  createRecord: 5,
  updateRecord: 6,
  deleteRecord: 7,
  verifyDomain: 8,
  listPagesProjects: 9,
  getPagesProject: 10,
  createPagesProject: 11,
  triggerPagesDeploy: 12,
  addPagesDomain: 13,
  removePagesDomain: 14,
} as const;

/** Typed RPC client for the Dns service over a ZAP call channel. */
export interface DnsChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class DnsClient {
  constructor(private readonly channel: DnsChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async listZones(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.listZones,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.listZones: status ${resp.status}`);
    }
    return resp.body;
  }

  async createZone(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.createZone,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.createZone: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteZone(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.deleteZone,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.deleteZone: status ${resp.status}`);
    }
    return resp.body;
  }

  async listRecords(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.listRecords,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.listRecords: status ${resp.status}`);
    }
    return resp.body;
  }

  async createRecord(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.createRecord,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.createRecord: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateRecord(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.updateRecord,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.updateRecord: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteRecord(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.deleteRecord,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.deleteRecord: status ${resp.status}`);
    }
    return resp.body;
  }

  async verifyDomain(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.verifyDomain,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.verifyDomain: status ${resp.status}`);
    }
    return resp.body;
  }

  async listPagesProjects(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.listPagesProjects,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.listPagesProjects: status ${resp.status}`);
    }
    return resp.body;
  }

  async getPagesProject(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.getPagesProject,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.getPagesProject: status ${resp.status}`);
    }
    return resp.body;
  }

  async createPagesProject(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.createPagesProject,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.createPagesProject: status ${resp.status}`);
    }
    return resp.body;
  }

  async triggerPagesDeploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.triggerPagesDeploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.triggerPagesDeploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async addPagesDomain(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.addPagesDomain,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.addPagesDomain: status ${resp.status}`);
    }
    return resp.body;
  }

  async removePagesDomain(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DnsMethod.removePagesDomain,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Dns.removePagesDomain: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Dns service. Subclass and implement each method. */
export abstract class DnsServer {
  abstract listZones(args: Uint8Array): Promise<Uint8Array>;
  abstract createZone(args: Uint8Array): Promise<Uint8Array>;
  abstract deleteZone(args: Uint8Array): Promise<Uint8Array>;
  abstract listRecords(args: Uint8Array): Promise<Uint8Array>;
  abstract createRecord(args: Uint8Array): Promise<Uint8Array>;
  abstract updateRecord(args: Uint8Array): Promise<Uint8Array>;
  abstract deleteRecord(args: Uint8Array): Promise<Uint8Array>;
  abstract verifyDomain(args: Uint8Array): Promise<Uint8Array>;
  abstract listPagesProjects(args: Uint8Array): Promise<Uint8Array>;
  abstract getPagesProject(args: Uint8Array): Promise<Uint8Array>;
  abstract createPagesProject(args: Uint8Array): Promise<Uint8Array>;
  abstract triggerPagesDeploy(args: Uint8Array): Promise<Uint8Array>;
  abstract addPagesDomain(args: Uint8Array): Promise<Uint8Array>;
  abstract removePagesDomain(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case DnsMethod.listZones: {
        const body = await this.listZones(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.createZone: {
        const body = await this.createZone(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.deleteZone: {
        const body = await this.deleteZone(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.listRecords: {
        const body = await this.listRecords(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.createRecord: {
        const body = await this.createRecord(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.updateRecord: {
        const body = await this.updateRecord(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.deleteRecord: {
        const body = await this.deleteRecord(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.verifyDomain: {
        const body = await this.verifyDomain(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.listPagesProjects: {
        const body = await this.listPagesProjects(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.getPagesProject: {
        const body = await this.getPagesProject(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.createPagesProject: {
        const body = await this.createPagesProject(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.triggerPagesDeploy: {
        const body = await this.triggerPagesDeploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.addPagesDomain: {
        const body = await this.addPagesDomain(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DnsMethod.removePagesDomain: {
        const body = await this.removePagesDomain(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


