// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: docker.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Docker service (stable wire ids). */
export const DockerMethod = {
  getContainers: 1,
  restartContainer: 2,
  startContainer: 3,
  stopContainer: 4,
  killContainer: 5,
  removeContainer: 6,
  getConfig: 7,
  getContainersByAppNameMatch: 8,
  getContainersByAppLabel: 9,
  getStackContainersByAppName: 10,
  getServiceContainersByAppName: 11,
  uploadFileToContainer: 12,
} as const;

/** Typed RPC client for the Docker service over a ZAP call channel. */
export interface DockerChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class DockerClient {
  constructor(private readonly channel: DockerChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async getContainers(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.getContainers,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.getContainers: status ${resp.status}`);
    }
    return resp.body;
  }

  async restartContainer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.restartContainer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.restartContainer: status ${resp.status}`);
    }
    return resp.body;
  }

  async startContainer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.startContainer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.startContainer: status ${resp.status}`);
    }
    return resp.body;
  }

  async stopContainer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.stopContainer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.stopContainer: status ${resp.status}`);
    }
    return resp.body;
  }

  async killContainer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.killContainer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.killContainer: status ${resp.status}`);
    }
    return resp.body;
  }

  async removeContainer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.removeContainer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.removeContainer: status ${resp.status}`);
    }
    return resp.body;
  }

  async getConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.getConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.getConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async getContainersByAppNameMatch(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.getContainersByAppNameMatch,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.getContainersByAppNameMatch: status ${resp.status}`);
    }
    return resp.body;
  }

  async getContainersByAppLabel(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.getContainersByAppLabel,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.getContainersByAppLabel: status ${resp.status}`);
    }
    return resp.body;
  }

  async getStackContainersByAppName(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.getStackContainersByAppName,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.getStackContainersByAppName: status ${resp.status}`);
    }
    return resp.body;
  }

  async getServiceContainersByAppName(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.getServiceContainersByAppName,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.getServiceContainersByAppName: status ${resp.status}`);
    }
    return resp.body;
  }

  async uploadFileToContainer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DockerMethod.uploadFileToContainer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Docker.uploadFileToContainer: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Docker service. Subclass and implement each method. */
export abstract class DockerServer {
  abstract getContainers(args: Uint8Array): Promise<Uint8Array>;
  abstract restartContainer(args: Uint8Array): Promise<Uint8Array>;
  abstract startContainer(args: Uint8Array): Promise<Uint8Array>;
  abstract stopContainer(args: Uint8Array): Promise<Uint8Array>;
  abstract killContainer(args: Uint8Array): Promise<Uint8Array>;
  abstract removeContainer(args: Uint8Array): Promise<Uint8Array>;
  abstract getConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract getContainersByAppNameMatch(args: Uint8Array): Promise<Uint8Array>;
  abstract getContainersByAppLabel(args: Uint8Array): Promise<Uint8Array>;
  abstract getStackContainersByAppName(args: Uint8Array): Promise<Uint8Array>;
  abstract getServiceContainersByAppName(args: Uint8Array): Promise<Uint8Array>;
  abstract uploadFileToContainer(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case DockerMethod.getContainers: {
        const body = await this.getContainers(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.restartContainer: {
        const body = await this.restartContainer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.startContainer: {
        const body = await this.startContainer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.stopContainer: {
        const body = await this.stopContainer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.killContainer: {
        const body = await this.killContainer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.removeContainer: {
        const body = await this.removeContainer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.getConfig: {
        const body = await this.getConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.getContainersByAppNameMatch: {
        const body = await this.getContainersByAppNameMatch(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.getContainersByAppLabel: {
        const body = await this.getContainersByAppLabel(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.getStackContainersByAppName: {
        const body = await this.getStackContainersByAppName(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.getServiceContainersByAppName: {
        const body = await this.getServiceContainersByAppName(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DockerMethod.uploadFileToContainer: {
        const body = await this.uploadFileToContainer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


