// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: doks.zap

import {
  Builder,
  Message,
  StructView,
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

const provisionParamsOff = {
  organizationId: 0,
  region: 8,
  nodeSize: 16,
  ha: 24,
  nodeCount: 28,
} as const;
const provisionParamsSize = 32;

/** Zero-copy view into a ZAP-encoded ProvisionParams message. */
export class ProvisionParams extends StructView {
  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */
  static wrap(b: Uint8Array): ProvisionParams {
    const root = Message.parse(b).root();
    return new ProvisionParams(root.data, root.offset);
  }

  get organizationId(): string { return this.text(provisionParamsOff.organizationId); }
  get region(): string { return this.text(provisionParamsOff.region); }
  get nodeSize(): string { return this.text(provisionParamsOff.nodeSize); }
  get ha(): boolean { return this.bool(provisionParamsOff.ha); }
  get nodeCount(): number { return this.u32(provisionParamsOff.nodeCount); }
}

/** Field values for newProvisionParams. */
export interface ProvisionParamsInput {
  organizationId: string;
  region: string;
  nodeSize: string;
  ha: boolean;
  nodeCount: number;
}

/** Build a ZAP-encoded ProvisionParams message from `in` and return the bytes. */
export function newProvisionParams(in_: ProvisionParamsInput): Uint8Array {
  const b = new Builder(256);
  const ob = b.startObject(provisionParamsSize);
  ob.setText(provisionParamsOff.organizationId, in_.organizationId);
  ob.setText(provisionParamsOff.region, in_.region);
  ob.setText(provisionParamsOff.nodeSize, in_.nodeSize);
  ob.setBool(provisionParamsOff.ha, in_.ha);
  ob.setU32(provisionParamsOff.nodeCount, in_.nodeCount);
  ob.finishAsRoot();
  return b.finish();
}


const clusterRefOff = {
  doksClusterId: 0,
} as const;
const clusterRefSize = 8;

/** Zero-copy view into a ZAP-encoded ClusterRef message. */
export class ClusterRef extends StructView {
  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */
  static wrap(b: Uint8Array): ClusterRef {
    const root = Message.parse(b).root();
    return new ClusterRef(root.data, root.offset);
  }

  get doksClusterId(): string { return this.text(clusterRefOff.doksClusterId); }
}

/** Field values for newClusterRef. */
export interface ClusterRefInput {
  doksClusterId: string;
}

/** Build a ZAP-encoded ClusterRef message from `in` and return the bytes. */
export function newClusterRef(in_: ClusterRefInput): Uint8Array {
  const b = new Builder(256);
  const ob = b.startObject(clusterRefSize);
  ob.setText(clusterRefOff.doksClusterId, in_.doksClusterId);
  ob.finishAsRoot();
  return b.finish();
}


const addNodePoolParamsOff = {
  doksClusterId: 0,
  name: 8,
  size: 16,
  count: 24,
} as const;
const addNodePoolParamsSize = 28;

/** Zero-copy view into a ZAP-encoded AddNodePoolParams message. */
export class AddNodePoolParams extends StructView {
  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */
  static wrap(b: Uint8Array): AddNodePoolParams {
    const root = Message.parse(b).root();
    return new AddNodePoolParams(root.data, root.offset);
  }

  get doksClusterId(): string { return this.text(addNodePoolParamsOff.doksClusterId); }
  get name(): string { return this.text(addNodePoolParamsOff.name); }
  get size(): string { return this.text(addNodePoolParamsOff.size); }
  get count(): number { return this.u32(addNodePoolParamsOff.count); }
}

/** Field values for newAddNodePoolParams. */
export interface AddNodePoolParamsInput {
  doksClusterId: string;
  name: string;
  size: string;
  count: number;
}

/** Build a ZAP-encoded AddNodePoolParams message from `in` and return the bytes. */
export function newAddNodePoolParams(in_: AddNodePoolParamsInput): Uint8Array {
  const b = new Builder(256);
  const ob = b.startObject(addNodePoolParamsSize);
  ob.setText(addNodePoolParamsOff.doksClusterId, in_.doksClusterId);
  ob.setText(addNodePoolParamsOff.name, in_.name);
  ob.setText(addNodePoolParamsOff.size, in_.size);
  ob.setU32(addNodePoolParamsOff.count, in_.count);
  ob.finishAsRoot();
  return b.finish();
}


const updateNodePoolParamsOff = {
  doksClusterId: 0,
  poolId: 8,
  size: 16,
  count: 24,
} as const;
const updateNodePoolParamsSize = 28;

/** Zero-copy view into a ZAP-encoded UpdateNodePoolParams message. */
export class UpdateNodePoolParams extends StructView {
  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */
  static wrap(b: Uint8Array): UpdateNodePoolParams {
    const root = Message.parse(b).root();
    return new UpdateNodePoolParams(root.data, root.offset);
  }

  get doksClusterId(): string { return this.text(updateNodePoolParamsOff.doksClusterId); }
  get poolId(): string { return this.text(updateNodePoolParamsOff.poolId); }
  get size(): string { return this.text(updateNodePoolParamsOff.size); }
  get count(): number { return this.u32(updateNodePoolParamsOff.count); }
}

/** Field values for newUpdateNodePoolParams. */
export interface UpdateNodePoolParamsInput {
  doksClusterId: string;
  poolId: string;
  size: string;
  count: number;
}

/** Build a ZAP-encoded UpdateNodePoolParams message from `in` and return the bytes. */
export function newUpdateNodePoolParams(in_: UpdateNodePoolParamsInput): Uint8Array {
  const b = new Builder(256);
  const ob = b.startObject(updateNodePoolParamsSize);
  ob.setText(updateNodePoolParamsOff.doksClusterId, in_.doksClusterId);
  ob.setText(updateNodePoolParamsOff.poolId, in_.poolId);
  ob.setText(updateNodePoolParamsOff.size, in_.size);
  ob.setU32(updateNodePoolParamsOff.count, in_.count);
  ob.finishAsRoot();
  return b.finish();
}


const deleteNodePoolParamsOff = {
  doksClusterId: 0,
  poolId: 8,
} as const;
const deleteNodePoolParamsSize = 16;

/** Zero-copy view into a ZAP-encoded DeleteNodePoolParams message. */
export class DeleteNodePoolParams extends StructView {
  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */
  static wrap(b: Uint8Array): DeleteNodePoolParams {
    const root = Message.parse(b).root();
    return new DeleteNodePoolParams(root.data, root.offset);
  }

  get doksClusterId(): string { return this.text(deleteNodePoolParamsOff.doksClusterId); }
  get poolId(): string { return this.text(deleteNodePoolParamsOff.poolId); }
}

/** Field values for newDeleteNodePoolParams. */
export interface DeleteNodePoolParamsInput {
  doksClusterId: string;
  poolId: string;
}

/** Build a ZAP-encoded DeleteNodePoolParams message from `in` and return the bytes. */
export function newDeleteNodePoolParams(in_: DeleteNodePoolParamsInput): Uint8Array {
  const b = new Builder(256);
  const ob = b.startObject(deleteNodePoolParamsSize);
  ob.setText(deleteNodePoolParamsOff.doksClusterId, in_.doksClusterId);
  ob.setText(deleteNodePoolParamsOff.poolId, in_.poolId);
  ob.finishAsRoot();
  return b.finish();
}


const emptyOff = {
  _pad: 0,
} as const;
const emptySize = 1;

/** Zero-copy view into a ZAP-encoded Empty message. */
export class Empty extends StructView {
  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */
  static wrap(b: Uint8Array): Empty {
    const root = Message.parse(b).root();
    return new Empty(root.data, root.offset);
  }

  get _pad(): number { return this.u8(emptyOff._pad); }
}

/** Field values for newEmpty. */
export interface EmptyInput {
  _pad: number;
}

/** Build a ZAP-encoded Empty message from `in` and return the bytes. */
export function newEmpty(in_: EmptyInput): Uint8Array {
  const b = new Builder(256);
  const ob = b.startObject(emptySize);
  ob.setU8(emptyOff._pad, in_._pad);
  ob.finishAsRoot();
  return b.finish();
}


/** Method ordinals for the Doks service (stable wire ids). */
export const DoksMethod = {
  provision: 1,
  get: 2,
  getByOrg: 3,
  status: 4,
  kubeconfig: 5,
  delete: 6,
  upgradeToHA: 7,
  addNodePool: 8,
  updateNodePool: 9,
  deleteNodePool: 10,
  list: 11,
  sync: 12,
  listNodeSizes: 13,
  listRegions: 14,
  clusterCost: 15,
  orgBilling: 16,
  fleetBilling: 17,
  recordSnapshot: 18,
} as const;

/** Typed RPC client for the Doks service over a ZAP call channel. */
export interface DoksChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class DoksClient {
  constructor(private readonly channel: DoksChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async provision(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.provision,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.provision: status ${resp.status}`);
    }
    return resp.body;
  }

  async get(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.get,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.get: status ${resp.status}`);
    }
    return resp.body;
  }

  async getByOrg(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.getByOrg,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.getByOrg: status ${resp.status}`);
    }
    return resp.body;
  }

  async status(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.status,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.status: status ${resp.status}`);
    }
    return resp.body;
  }

  async kubeconfig(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.kubeconfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.kubeconfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async upgradeToHA(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.upgradeToHA,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.upgradeToHA: status ${resp.status}`);
    }
    return resp.body;
  }

  async addNodePool(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.addNodePool,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.addNodePool: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateNodePool(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.updateNodePool,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.updateNodePool: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteNodePool(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.deleteNodePool,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.deleteNodePool: status ${resp.status}`);
    }
    return resp.body;
  }

  async list(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.list,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.list: status ${resp.status}`);
    }
    return resp.body;
  }

  async sync(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.sync,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.sync: status ${resp.status}`);
    }
    return resp.body;
  }

  async listNodeSizes(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.listNodeSizes,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.listNodeSizes: status ${resp.status}`);
    }
    return resp.body;
  }

  async listRegions(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.listRegions,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.listRegions: status ${resp.status}`);
    }
    return resp.body;
  }

  async clusterCost(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.clusterCost,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.clusterCost: status ${resp.status}`);
    }
    return resp.body;
  }

  async orgBilling(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.orgBilling,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.orgBilling: status ${resp.status}`);
    }
    return resp.body;
  }

  async fleetBilling(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.fleetBilling,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.fleetBilling: status ${resp.status}`);
    }
    return resp.body;
  }

  async recordSnapshot(params: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DoksMethod.recordSnapshot,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: params,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Doks.recordSnapshot: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Doks service. Subclass and implement each method. */
export abstract class DoksServer {
  abstract provision(params: Uint8Array): Promise<Uint8Array>;
  abstract get(params: Uint8Array): Promise<Uint8Array>;
  abstract getByOrg(params: Uint8Array): Promise<Uint8Array>;
  abstract status(params: Uint8Array): Promise<Uint8Array>;
  abstract kubeconfig(params: Uint8Array): Promise<Uint8Array>;
  abstract delete(params: Uint8Array): Promise<Uint8Array>;
  abstract upgradeToHA(params: Uint8Array): Promise<Uint8Array>;
  abstract addNodePool(params: Uint8Array): Promise<Uint8Array>;
  abstract updateNodePool(params: Uint8Array): Promise<Uint8Array>;
  abstract deleteNodePool(params: Uint8Array): Promise<Uint8Array>;
  abstract list(params: Uint8Array): Promise<Uint8Array>;
  abstract sync(params: Uint8Array): Promise<Uint8Array>;
  abstract listNodeSizes(params: Uint8Array): Promise<Uint8Array>;
  abstract listRegions(params: Uint8Array): Promise<Uint8Array>;
  abstract clusterCost(params: Uint8Array): Promise<Uint8Array>;
  abstract orgBilling(params: Uint8Array): Promise<Uint8Array>;
  abstract fleetBilling(params: Uint8Array): Promise<Uint8Array>;
  abstract recordSnapshot(params: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case DoksMethod.provision: {
        const body = await this.provision(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.get: {
        const body = await this.get(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.getByOrg: {
        const body = await this.getByOrg(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.status: {
        const body = await this.status(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.kubeconfig: {
        const body = await this.kubeconfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.upgradeToHA: {
        const body = await this.upgradeToHA(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.addNodePool: {
        const body = await this.addNodePool(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.updateNodePool: {
        const body = await this.updateNodePool(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.deleteNodePool: {
        const body = await this.deleteNodePool(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.list: {
        const body = await this.list(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.sync: {
        const body = await this.sync(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.listNodeSizes: {
        const body = await this.listNodeSizes(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.listRegions: {
        const body = await this.listRegions(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.clusterCost: {
        const body = await this.clusterCost(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.orgBilling: {
        const body = await this.orgBilling(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.fleetBilling: {
        const body = await this.fleetBilling(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DoksMethod.recordSnapshot: {
        const body = await this.recordSnapshot(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


