// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: domain.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Domain service (stable wire ids). */
export const DomainMethod = {
  create: 1,
  byApplicationId: 2,
  byComposeId: 3,
  generateDomain: 4,
  canGenerateTraefikMeDomains: 5,
  update: 6,
  one: 7,
  delete: 8,
  validateDomain: 9,
} as const;

/** Typed RPC client for the Domain service over a ZAP call channel. */
export interface DomainChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class DomainClient {
  constructor(private readonly channel: DomainChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async byApplicationId(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.byApplicationId,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.byApplicationId: status ${resp.status}`);
    }
    return resp.body;
  }

  async byComposeId(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.byComposeId,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.byComposeId: status ${resp.status}`);
    }
    return resp.body;
  }

  async generateDomain(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.generateDomain,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.generateDomain: status ${resp.status}`);
    }
    return resp.body;
  }

  async canGenerateTraefikMeDomains(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.canGenerateTraefikMeDomains,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.canGenerateTraefikMeDomains: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async validateDomain(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: DomainMethod.validateDomain,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Domain.validateDomain: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Domain service. Subclass and implement each method. */
export abstract class DomainServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract byApplicationId(args: Uint8Array): Promise<Uint8Array>;
  abstract byComposeId(args: Uint8Array): Promise<Uint8Array>;
  abstract generateDomain(args: Uint8Array): Promise<Uint8Array>;
  abstract canGenerateTraefikMeDomains(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract validateDomain(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case DomainMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.byApplicationId: {
        const body = await this.byApplicationId(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.byComposeId: {
        const body = await this.byComposeId(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.generateDomain: {
        const body = await this.generateDomain(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.canGenerateTraefikMeDomains: {
        const body = await this.canGenerateTraefikMeDomains(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case DomainMethod.validateDomain: {
        const body = await this.validateDomain(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


