// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: environment.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Environment service (stable wire ids). */
export const EnvironmentMethod = {
  create: 1,
  one: 2,
  byProjectId: 3,
  remove: 4,
  update: 5,
  duplicate: 6,
  search: 7,
} as const;

/** Typed RPC client for the Environment service over a ZAP call channel. */
export interface EnvironmentChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class EnvironmentClient {
  constructor(private readonly channel: EnvironmentChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: EnvironmentMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Environment.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: EnvironmentMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Environment.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async byProjectId(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: EnvironmentMethod.byProjectId,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Environment.byProjectId: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: EnvironmentMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Environment.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: EnvironmentMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Environment.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async duplicate(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: EnvironmentMethod.duplicate,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Environment.duplicate: status ${resp.status}`);
    }
    return resp.body;
  }

  async search(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: EnvironmentMethod.search,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Environment.search: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Environment service. Subclass and implement each method. */
export abstract class EnvironmentServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract byProjectId(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract duplicate(args: Uint8Array): Promise<Uint8Array>;
  abstract search(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case EnvironmentMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case EnvironmentMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case EnvironmentMethod.byProjectId: {
        const body = await this.byProjectId(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case EnvironmentMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case EnvironmentMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case EnvironmentMethod.duplicate: {
        const body = await this.duplicate(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case EnvironmentMethod.search: {
        const body = await this.search(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


