// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: git-provider.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the GitProvider service (stable wire ids). */
export const GitProviderMethod = {
  getAll: 1,
  toggleShare: 2,
  allForPermissions: 3,
  remove: 4,
} as const;

/** Typed RPC client for the GitProvider service over a ZAP call channel. */
export interface GitProviderChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class GitProviderClient {
  constructor(private readonly channel: GitProviderChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async getAll(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitProviderMethod.getAll,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`GitProvider.getAll: status ${resp.status}`);
    }
    return resp.body;
  }

  async toggleShare(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitProviderMethod.toggleShare,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`GitProvider.toggleShare: status ${resp.status}`);
    }
    return resp.body;
  }

  async allForPermissions(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitProviderMethod.allForPermissions,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`GitProvider.allForPermissions: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitProviderMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`GitProvider.remove: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the GitProvider service. Subclass and implement each method. */
export abstract class GitProviderServer {
  abstract getAll(args: Uint8Array): Promise<Uint8Array>;
  abstract toggleShare(args: Uint8Array): Promise<Uint8Array>;
  abstract allForPermissions(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case GitProviderMethod.getAll: {
        const body = await this.getAll(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitProviderMethod.toggleShare: {
        const body = await this.toggleShare(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitProviderMethod.allForPermissions: {
        const body = await this.allForPermissions(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitProviderMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


