// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: gitea.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Gitea service (stable wire ids). */
export const GiteaMethod = {
  create: 1,
  one: 2,
  giteaProviders: 3,
  getGiteaRepositories: 4,
  getGiteaBranches: 5,
  testConnection: 6,
  update: 7,
  getGiteaUrl: 8,
} as const;

/** Typed RPC client for the Gitea service over a ZAP call channel. */
export interface GiteaChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class GiteaClient {
  constructor(private readonly channel: GiteaChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async giteaProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.giteaProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.giteaProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async getGiteaRepositories(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.getGiteaRepositories,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.getGiteaRepositories: status ${resp.status}`);
    }
    return resp.body;
  }

  async getGiteaBranches(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.getGiteaBranches,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.getGiteaBranches: status ${resp.status}`);
    }
    return resp.body;
  }

  async testConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.testConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.testConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async getGiteaUrl(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GiteaMethod.getGiteaUrl,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitea.getGiteaUrl: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Gitea service. Subclass and implement each method. */
export abstract class GiteaServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract giteaProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract getGiteaRepositories(args: Uint8Array): Promise<Uint8Array>;
  abstract getGiteaBranches(args: Uint8Array): Promise<Uint8Array>;
  abstract testConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract getGiteaUrl(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case GiteaMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GiteaMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GiteaMethod.giteaProviders: {
        const body = await this.giteaProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GiteaMethod.getGiteaRepositories: {
        const body = await this.getGiteaRepositories(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GiteaMethod.getGiteaBranches: {
        const body = await this.getGiteaBranches(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GiteaMethod.testConnection: {
        const body = await this.testConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GiteaMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GiteaMethod.getGiteaUrl: {
        const body = await this.getGiteaUrl(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


