// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: github.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Github service (stable wire ids). */
export const GithubMethod = {
  one: 1,
  getGithubRepositories: 2,
  getGithubBranches: 3,
  githubProviders: 4,
  testConnection: 5,
  update: 6,
} as const;

/** Typed RPC client for the Github service over a ZAP call channel. */
export interface GithubChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class GithubClient {
  constructor(private readonly channel: GithubChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GithubMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Github.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async getGithubRepositories(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GithubMethod.getGithubRepositories,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Github.getGithubRepositories: status ${resp.status}`);
    }
    return resp.body;
  }

  async getGithubBranches(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GithubMethod.getGithubBranches,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Github.getGithubBranches: status ${resp.status}`);
    }
    return resp.body;
  }

  async githubProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GithubMethod.githubProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Github.githubProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async testConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GithubMethod.testConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Github.testConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GithubMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Github.update: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Github service. Subclass and implement each method. */
export abstract class GithubServer {
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract getGithubRepositories(args: Uint8Array): Promise<Uint8Array>;
  abstract getGithubBranches(args: Uint8Array): Promise<Uint8Array>;
  abstract githubProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract testConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case GithubMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GithubMethod.getGithubRepositories: {
        const body = await this.getGithubRepositories(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GithubMethod.getGithubBranches: {
        const body = await this.getGithubBranches(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GithubMethod.githubProviders: {
        const body = await this.githubProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GithubMethod.testConnection: {
        const body = await this.testConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GithubMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


