// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: gitlab.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Gitlab service (stable wire ids). */
export const GitlabMethod = {
  create: 1,
  one: 2,
  gitlabProviders: 3,
  getGitlabRepositories: 4,
  getGitlabBranches: 5,
  testConnection: 6,
  update: 7,
} as const;

/** Typed RPC client for the Gitlab service over a ZAP call channel. */
export interface GitlabChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class GitlabClient {
  constructor(private readonly channel: GitlabChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitlabMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitlab.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitlabMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitlab.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async gitlabProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitlabMethod.gitlabProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitlab.gitlabProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async getGitlabRepositories(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitlabMethod.getGitlabRepositories,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitlab.getGitlabRepositories: status ${resp.status}`);
    }
    return resp.body;
  }

  async getGitlabBranches(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitlabMethod.getGitlabBranches,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitlab.getGitlabBranches: status ${resp.status}`);
    }
    return resp.body;
  }

  async testConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitlabMethod.testConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitlab.testConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: GitlabMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Gitlab.update: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Gitlab service. Subclass and implement each method. */
export abstract class GitlabServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract gitlabProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract getGitlabRepositories(args: Uint8Array): Promise<Uint8Array>;
  abstract getGitlabBranches(args: Uint8Array): Promise<Uint8Array>;
  abstract testConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case GitlabMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitlabMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitlabMethod.gitlabProviders: {
        const body = await this.gitlabProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitlabMethod.getGitlabRepositories: {
        const body = await this.getGitlabRepositories(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitlabMethod.getGitlabBranches: {
        const body = await this.getGitlabBranches(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitlabMethod.testConnection: {
        const body = await this.testConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case GitlabMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


