// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: k8s.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the K8s service (stable wire ids). */
export const K8sMethod = {
  deploy: 1,
  teardown: 2,
  status: 3,
  logs: 4,
  deployStack: 5,
} as const;

/** Typed RPC client for the K8s service over a ZAP call channel. */
export interface K8sChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class K8sClient {
  constructor(private readonly channel: K8sChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async deploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: K8sMethod.deploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`K8s.deploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async teardown(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: K8sMethod.teardown,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`K8s.teardown: status ${resp.status}`);
    }
    return resp.body;
  }

  async status(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: K8sMethod.status,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`K8s.status: status ${resp.status}`);
    }
    return resp.body;
  }

  async logs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: K8sMethod.logs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`K8s.logs: status ${resp.status}`);
    }
    return resp.body;
  }

  async deployStack(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: K8sMethod.deployStack,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`K8s.deployStack: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the K8s service. Subclass and implement each method. */
export abstract class K8sServer {
  abstract deploy(args: Uint8Array): Promise<Uint8Array>;
  abstract teardown(args: Uint8Array): Promise<Uint8Array>;
  abstract status(args: Uint8Array): Promise<Uint8Array>;
  abstract logs(args: Uint8Array): Promise<Uint8Array>;
  abstract deployStack(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case K8sMethod.deploy: {
        const body = await this.deploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case K8sMethod.teardown: {
        const body = await this.teardown(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case K8sMethod.status: {
        const body = await this.status(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case K8sMethod.logs: {
        const body = await this.logs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case K8sMethod.deployStack: {
        const body = await this.deployStack(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


