// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: mongo.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Mongo service (stable wire ids). */
export const MongoMethod = {
  create: 1,
  one: 2,
  start: 3,
  stop: 4,
  saveExternalPort: 5,
  deploy: 6,
  deployWithLogs: 7,
  changeStatus: 8,
  reload: 9,
  remove: 10,
  saveEnvironment: 11,
  update: 12,
  changePassword: 13,
  move: 14,
  rebuild: 15,
  search: 16,
  readLogs: 17,
} as const;

/** Typed RPC client for the Mongo service over a ZAP call channel. */
export interface MongoChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class MongoClient {
  constructor(private readonly channel: MongoChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async start(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.start,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.start: status ${resp.status}`);
    }
    return resp.body;
  }

  async stop(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.stop,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.stop: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveExternalPort(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.saveExternalPort,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.saveExternalPort: status ${resp.status}`);
    }
    return resp.body;
  }

  async deploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.deploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.deploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async deployWithLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.deployWithLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.deployWithLogs: status ${resp.status}`);
    }
    return resp.body;
  }

  async changeStatus(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.changeStatus,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.changeStatus: status ${resp.status}`);
    }
    return resp.body;
  }

  async reload(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.reload,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.reload: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveEnvironment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.saveEnvironment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.saveEnvironment: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async changePassword(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.changePassword,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.changePassword: status ${resp.status}`);
    }
    return resp.body;
  }

  async move(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.move,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.move: status ${resp.status}`);
    }
    return resp.body;
  }

  async rebuild(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.rebuild,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.rebuild: status ${resp.status}`);
    }
    return resp.body;
  }

  async search(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.search,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.search: status ${resp.status}`);
    }
    return resp.body;
  }

  async readLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MongoMethod.readLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mongo.readLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Mongo service. Subclass and implement each method. */
export abstract class MongoServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract start(args: Uint8Array): Promise<Uint8Array>;
  abstract stop(args: Uint8Array): Promise<Uint8Array>;
  abstract saveExternalPort(args: Uint8Array): Promise<Uint8Array>;
  abstract deploy(args: Uint8Array): Promise<Uint8Array>;
  abstract deployWithLogs(args: Uint8Array): Promise<Uint8Array>;
  abstract changeStatus(args: Uint8Array): Promise<Uint8Array>;
  abstract reload(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract saveEnvironment(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract changePassword(args: Uint8Array): Promise<Uint8Array>;
  abstract move(args: Uint8Array): Promise<Uint8Array>;
  abstract rebuild(args: Uint8Array): Promise<Uint8Array>;
  abstract search(args: Uint8Array): Promise<Uint8Array>;
  abstract readLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case MongoMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.start: {
        const body = await this.start(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.stop: {
        const body = await this.stop(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.saveExternalPort: {
        const body = await this.saveExternalPort(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.deploy: {
        const body = await this.deploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.deployWithLogs: {
        const body = await this.deployWithLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.changeStatus: {
        const body = await this.changeStatus(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.reload: {
        const body = await this.reload(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.saveEnvironment: {
        const body = await this.saveEnvironment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.changePassword: {
        const body = await this.changePassword(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.move: {
        const body = await this.move(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.rebuild: {
        const body = await this.rebuild(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.search: {
        const body = await this.search(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MongoMethod.readLogs: {
        const body = await this.readLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


