// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: mount.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Mount service (stable wire ids). */
export const MountMethod = {
  create: 1,
  remove: 2,
  one: 3,
  update: 4,
  allNamedByApplicationId: 5,
  listByServiceId: 6,
} as const;

/** Typed RPC client for the Mount service over a ZAP call channel. */
export interface MountChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class MountClient {
  constructor(private readonly channel: MountChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MountMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mount.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MountMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mount.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MountMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mount.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MountMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mount.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async allNamedByApplicationId(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MountMethod.allNamedByApplicationId,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mount.allNamedByApplicationId: status ${resp.status}`);
    }
    return resp.body;
  }

  async listByServiceId(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: MountMethod.listByServiceId,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Mount.listByServiceId: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Mount service. Subclass and implement each method. */
export abstract class MountServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract allNamedByApplicationId(args: Uint8Array): Promise<Uint8Array>;
  abstract listByServiceId(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case MountMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MountMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MountMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MountMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MountMethod.allNamedByApplicationId: {
        const body = await this.allNamedByApplicationId(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case MountMethod.listByServiceId: {
        const body = await this.listByServiceId(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


