// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: notification.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Notification service (stable wire ids). */
export const NotificationMethod = {
  createSlack: 1,
  updateSlack: 2,
  testSlackConnection: 3,
  createTelegram: 4,
  updateTelegram: 5,
  testTelegramConnection: 6,
  createDiscord: 7,
  updateDiscord: 8,
  testDiscordConnection: 9,
  createEmail: 10,
  updateEmail: 11,
  testEmailConnection: 12,
  createResend: 13,
  updateResend: 14,
  testResendConnection: 15,
  remove: 16,
  one: 17,
  all: 18,
  createGotify: 19,
  updateGotify: 20,
  testGotifyConnection: 21,
  createNtfy: 22,
  updateNtfy: 23,
  testNtfyConnection: 24,
  createMattermost: 25,
  updateMattermost: 26,
  testMattermostConnection: 27,
  createCustom: 28,
  updateCustom: 29,
  testCustomConnection: 30,
  createLark: 31,
  updateLark: 32,
  testLarkConnection: 33,
  createTeams: 34,
  updateTeams: 35,
  testTeamsConnection: 36,
  createPushover: 37,
  updatePushover: 38,
  testPushoverConnection: 39,
  getEmailProviders: 40,
} as const;

/** Typed RPC client for the Notification service over a ZAP call channel. */
export interface NotificationChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class NotificationClient {
  constructor(private readonly channel: NotificationChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async createSlack(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createSlack,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createSlack: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateSlack(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateSlack,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateSlack: status ${resp.status}`);
    }
    return resp.body;
  }

  async testSlackConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testSlackConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testSlackConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createTelegram(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createTelegram,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createTelegram: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateTelegram(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateTelegram,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateTelegram: status ${resp.status}`);
    }
    return resp.body;
  }

  async testTelegramConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testTelegramConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testTelegramConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createDiscord(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createDiscord,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createDiscord: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateDiscord(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateDiscord,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateDiscord: status ${resp.status}`);
    }
    return resp.body;
  }

  async testDiscordConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testDiscordConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testDiscordConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createEmail(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createEmail,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createEmail: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateEmail(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateEmail,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateEmail: status ${resp.status}`);
    }
    return resp.body;
  }

  async testEmailConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testEmailConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testEmailConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createResend(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createResend,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createResend: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateResend(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateResend,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateResend: status ${resp.status}`);
    }
    return resp.body;
  }

  async testResendConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testResendConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testResendConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async createGotify(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createGotify,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createGotify: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateGotify(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateGotify,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateGotify: status ${resp.status}`);
    }
    return resp.body;
  }

  async testGotifyConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testGotifyConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testGotifyConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createNtfy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createNtfy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createNtfy: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateNtfy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateNtfy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateNtfy: status ${resp.status}`);
    }
    return resp.body;
  }

  async testNtfyConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testNtfyConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testNtfyConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createMattermost(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createMattermost,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createMattermost: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateMattermost(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateMattermost,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateMattermost: status ${resp.status}`);
    }
    return resp.body;
  }

  async testMattermostConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testMattermostConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testMattermostConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createCustom(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createCustom,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createCustom: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateCustom(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateCustom,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateCustom: status ${resp.status}`);
    }
    return resp.body;
  }

  async testCustomConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testCustomConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testCustomConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createLark(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createLark,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createLark: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateLark(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateLark,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateLark: status ${resp.status}`);
    }
    return resp.body;
  }

  async testLarkConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testLarkConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testLarkConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createTeams(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createTeams,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createTeams: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateTeams(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updateTeams,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updateTeams: status ${resp.status}`);
    }
    return resp.body;
  }

  async testTeamsConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testTeamsConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testTeamsConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async createPushover(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.createPushover,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.createPushover: status ${resp.status}`);
    }
    return resp.body;
  }

  async updatePushover(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.updatePushover,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.updatePushover: status ${resp.status}`);
    }
    return resp.body;
  }

  async testPushoverConnection(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.testPushoverConnection,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.testPushoverConnection: status ${resp.status}`);
    }
    return resp.body;
  }

  async getEmailProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: NotificationMethod.getEmailProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Notification.getEmailProviders: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Notification service. Subclass and implement each method. */
export abstract class NotificationServer {
  abstract createSlack(args: Uint8Array): Promise<Uint8Array>;
  abstract updateSlack(args: Uint8Array): Promise<Uint8Array>;
  abstract testSlackConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createTelegram(args: Uint8Array): Promise<Uint8Array>;
  abstract updateTelegram(args: Uint8Array): Promise<Uint8Array>;
  abstract testTelegramConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createDiscord(args: Uint8Array): Promise<Uint8Array>;
  abstract updateDiscord(args: Uint8Array): Promise<Uint8Array>;
  abstract testDiscordConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createEmail(args: Uint8Array): Promise<Uint8Array>;
  abstract updateEmail(args: Uint8Array): Promise<Uint8Array>;
  abstract testEmailConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createResend(args: Uint8Array): Promise<Uint8Array>;
  abstract updateResend(args: Uint8Array): Promise<Uint8Array>;
  abstract testResendConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract createGotify(args: Uint8Array): Promise<Uint8Array>;
  abstract updateGotify(args: Uint8Array): Promise<Uint8Array>;
  abstract testGotifyConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createNtfy(args: Uint8Array): Promise<Uint8Array>;
  abstract updateNtfy(args: Uint8Array): Promise<Uint8Array>;
  abstract testNtfyConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createMattermost(args: Uint8Array): Promise<Uint8Array>;
  abstract updateMattermost(args: Uint8Array): Promise<Uint8Array>;
  abstract testMattermostConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createCustom(args: Uint8Array): Promise<Uint8Array>;
  abstract updateCustom(args: Uint8Array): Promise<Uint8Array>;
  abstract testCustomConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createLark(args: Uint8Array): Promise<Uint8Array>;
  abstract updateLark(args: Uint8Array): Promise<Uint8Array>;
  abstract testLarkConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createTeams(args: Uint8Array): Promise<Uint8Array>;
  abstract updateTeams(args: Uint8Array): Promise<Uint8Array>;
  abstract testTeamsConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract createPushover(args: Uint8Array): Promise<Uint8Array>;
  abstract updatePushover(args: Uint8Array): Promise<Uint8Array>;
  abstract testPushoverConnection(args: Uint8Array): Promise<Uint8Array>;
  abstract getEmailProviders(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case NotificationMethod.createSlack: {
        const body = await this.createSlack(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateSlack: {
        const body = await this.updateSlack(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testSlackConnection: {
        const body = await this.testSlackConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createTelegram: {
        const body = await this.createTelegram(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateTelegram: {
        const body = await this.updateTelegram(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testTelegramConnection: {
        const body = await this.testTelegramConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createDiscord: {
        const body = await this.createDiscord(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateDiscord: {
        const body = await this.updateDiscord(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testDiscordConnection: {
        const body = await this.testDiscordConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createEmail: {
        const body = await this.createEmail(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateEmail: {
        const body = await this.updateEmail(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testEmailConnection: {
        const body = await this.testEmailConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createResend: {
        const body = await this.createResend(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateResend: {
        const body = await this.updateResend(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testResendConnection: {
        const body = await this.testResendConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createGotify: {
        const body = await this.createGotify(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateGotify: {
        const body = await this.updateGotify(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testGotifyConnection: {
        const body = await this.testGotifyConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createNtfy: {
        const body = await this.createNtfy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateNtfy: {
        const body = await this.updateNtfy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testNtfyConnection: {
        const body = await this.testNtfyConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createMattermost: {
        const body = await this.createMattermost(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateMattermost: {
        const body = await this.updateMattermost(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testMattermostConnection: {
        const body = await this.testMattermostConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createCustom: {
        const body = await this.createCustom(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateCustom: {
        const body = await this.updateCustom(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testCustomConnection: {
        const body = await this.testCustomConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createLark: {
        const body = await this.createLark(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateLark: {
        const body = await this.updateLark(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testLarkConnection: {
        const body = await this.testLarkConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createTeams: {
        const body = await this.createTeams(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updateTeams: {
        const body = await this.updateTeams(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testTeamsConnection: {
        const body = await this.testTeamsConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.createPushover: {
        const body = await this.createPushover(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.updatePushover: {
        const body = await this.updatePushover(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.testPushoverConnection: {
        const body = await this.testPushoverConnection(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case NotificationMethod.getEmailProviders: {
        const body = await this.getEmailProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


