// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: organization.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Organization service (stable wire ids). */
export const OrganizationMethod = {
  create: 1,
  all: 2,
  one: 3,
  update: 4,
  delete: 5,
  allInvitations: 6,
  removeInvitation: 7,
} as const;

/** Typed RPC client for the Organization service over a ZAP call channel. */
export interface OrganizationChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class OrganizationClient {
  constructor(private readonly channel: OrganizationChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: OrganizationMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Organization.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: OrganizationMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Organization.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: OrganizationMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Organization.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: OrganizationMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Organization.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: OrganizationMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Organization.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async allInvitations(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: OrganizationMethod.allInvitations,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Organization.allInvitations: status ${resp.status}`);
    }
    return resp.body;
  }

  async removeInvitation(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: OrganizationMethod.removeInvitation,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Organization.removeInvitation: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Organization service. Subclass and implement each method. */
export abstract class OrganizationServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract allInvitations(args: Uint8Array): Promise<Uint8Array>;
  abstract removeInvitation(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case OrganizationMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case OrganizationMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case OrganizationMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case OrganizationMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case OrganizationMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case OrganizationMethod.allInvitations: {
        const body = await this.allInvitations(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case OrganizationMethod.removeInvitation: {
        const body = await this.removeInvitation(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


