// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: patch.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Patch service (stable wire ids). */
export const PatchMethod = {
  create: 1,
  one: 2,
  byEntityId: 3,
  update: 4,
  delete: 5,
  toggleEnabled: 6,
  ensureRepo: 7,
  readRepoDirectories: 8,
  readRepoFile: 9,
  saveFileAsPatch: 10,
  markFileForDeletion: 11,
  cleanPatchRepos: 12,
} as const;

/** Typed RPC client for the Patch service over a ZAP call channel. */
export interface PatchChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class PatchClient {
  constructor(private readonly channel: PatchChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async byEntityId(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.byEntityId,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.byEntityId: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async toggleEnabled(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.toggleEnabled,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.toggleEnabled: status ${resp.status}`);
    }
    return resp.body;
  }

  async ensureRepo(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.ensureRepo,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.ensureRepo: status ${resp.status}`);
    }
    return resp.body;
  }

  async readRepoDirectories(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.readRepoDirectories,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.readRepoDirectories: status ${resp.status}`);
    }
    return resp.body;
  }

  async readRepoFile(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.readRepoFile,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.readRepoFile: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveFileAsPatch(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.saveFileAsPatch,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.saveFileAsPatch: status ${resp.status}`);
    }
    return resp.body;
  }

  async markFileForDeletion(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.markFileForDeletion,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.markFileForDeletion: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanPatchRepos(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PatchMethod.cleanPatchRepos,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Patch.cleanPatchRepos: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Patch service. Subclass and implement each method. */
export abstract class PatchServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract byEntityId(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract toggleEnabled(args: Uint8Array): Promise<Uint8Array>;
  abstract ensureRepo(args: Uint8Array): Promise<Uint8Array>;
  abstract readRepoDirectories(args: Uint8Array): Promise<Uint8Array>;
  abstract readRepoFile(args: Uint8Array): Promise<Uint8Array>;
  abstract saveFileAsPatch(args: Uint8Array): Promise<Uint8Array>;
  abstract markFileForDeletion(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanPatchRepos(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case PatchMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.byEntityId: {
        const body = await this.byEntityId(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.toggleEnabled: {
        const body = await this.toggleEnabled(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.ensureRepo: {
        const body = await this.ensureRepo(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.readRepoDirectories: {
        const body = await this.readRepoDirectories(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.readRepoFile: {
        const body = await this.readRepoFile(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.saveFileAsPatch: {
        const body = await this.saveFileAsPatch(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.markFileForDeletion: {
        const body = await this.markFileForDeletion(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PatchMethod.cleanPatchRepos: {
        const body = await this.cleanPatchRepos(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


