// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: postgres.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Postgres service (stable wire ids). */
export const PostgresMethod = {
  create: 1,
  one: 2,
  start: 3,
  stop: 4,
  saveExternalPort: 5,
  deploy: 6,
  deployWithLogs: 7,
  changeStatus: 8,
  remove: 9,
  saveEnvironment: 10,
  reload: 11,
  update: 12,
  changePassword: 13,
  move: 14,
  rebuild: 15,
  search: 16,
  readLogs: 17,
} as const;

/** Typed RPC client for the Postgres service over a ZAP call channel. */
export interface PostgresChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class PostgresClient {
  constructor(private readonly channel: PostgresChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async start(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.start,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.start: status ${resp.status}`);
    }
    return resp.body;
  }

  async stop(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.stop,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.stop: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveExternalPort(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.saveExternalPort,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.saveExternalPort: status ${resp.status}`);
    }
    return resp.body;
  }

  async deploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.deploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.deploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async deployWithLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.deployWithLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.deployWithLogs: status ${resp.status}`);
    }
    return resp.body;
  }

  async changeStatus(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.changeStatus,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.changeStatus: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveEnvironment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.saveEnvironment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.saveEnvironment: status ${resp.status}`);
    }
    return resp.body;
  }

  async reload(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.reload,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.reload: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async changePassword(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.changePassword,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.changePassword: status ${resp.status}`);
    }
    return resp.body;
  }

  async move(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.move,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.move: status ${resp.status}`);
    }
    return resp.body;
  }

  async rebuild(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.rebuild,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.rebuild: status ${resp.status}`);
    }
    return resp.body;
  }

  async search(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.search,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.search: status ${resp.status}`);
    }
    return resp.body;
  }

  async readLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PostgresMethod.readLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Postgres.readLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Postgres service. Subclass and implement each method. */
export abstract class PostgresServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract start(args: Uint8Array): Promise<Uint8Array>;
  abstract stop(args: Uint8Array): Promise<Uint8Array>;
  abstract saveExternalPort(args: Uint8Array): Promise<Uint8Array>;
  abstract deploy(args: Uint8Array): Promise<Uint8Array>;
  abstract deployWithLogs(args: Uint8Array): Promise<Uint8Array>;
  abstract changeStatus(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract saveEnvironment(args: Uint8Array): Promise<Uint8Array>;
  abstract reload(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract changePassword(args: Uint8Array): Promise<Uint8Array>;
  abstract move(args: Uint8Array): Promise<Uint8Array>;
  abstract rebuild(args: Uint8Array): Promise<Uint8Array>;
  abstract search(args: Uint8Array): Promise<Uint8Array>;
  abstract readLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case PostgresMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.start: {
        const body = await this.start(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.stop: {
        const body = await this.stop(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.saveExternalPort: {
        const body = await this.saveExternalPort(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.deploy: {
        const body = await this.deploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.deployWithLogs: {
        const body = await this.deployWithLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.changeStatus: {
        const body = await this.changeStatus(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.saveEnvironment: {
        const body = await this.saveEnvironment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.reload: {
        const body = await this.reload(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.changePassword: {
        const body = await this.changePassword(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.move: {
        const body = await this.move(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.rebuild: {
        const body = await this.rebuild(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.search: {
        const body = await this.search(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PostgresMethod.readLogs: {
        const body = await this.readLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


