// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: preview-deployment.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the PreviewDeployment service (stable wire ids). */
export const PreviewDeploymentMethod = {
  all: 1,
  one: 2,
  delete: 3,
  redeploy: 4,
} as const;

/** Typed RPC client for the PreviewDeployment service over a ZAP call channel. */
export interface PreviewDeploymentChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class PreviewDeploymentClient {
  constructor(private readonly channel: PreviewDeploymentChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PreviewDeploymentMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`PreviewDeployment.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PreviewDeploymentMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`PreviewDeployment.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PreviewDeploymentMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`PreviewDeployment.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async redeploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: PreviewDeploymentMethod.redeploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`PreviewDeployment.redeploy: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the PreviewDeployment service. Subclass and implement each method. */
export abstract class PreviewDeploymentServer {
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract redeploy(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case PreviewDeploymentMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PreviewDeploymentMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PreviewDeploymentMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case PreviewDeploymentMethod.redeploy: {
        const body = await this.redeploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


