// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: project.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Project service (stable wire ids). */
export const ProjectMethod = {
  create: 1,
  one: 2,
  all: 3,
  allForPermissions: 4,
  homeStats: 5,
  search: 6,
  remove: 7,
  update: 8,
  duplicate: 9,
} as const;

/** Typed RPC client for the Project service over a ZAP call channel. */
export interface ProjectChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class ProjectClient {
  constructor(private readonly channel: ProjectChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async allForPermissions(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.allForPermissions,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.allForPermissions: status ${resp.status}`);
    }
    return resp.body;
  }

  async homeStats(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.homeStats,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.homeStats: status ${resp.status}`);
    }
    return resp.body;
  }

  async search(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.search,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.search: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async duplicate(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ProjectMethod.duplicate,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Project.duplicate: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Project service. Subclass and implement each method. */
export abstract class ProjectServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract allForPermissions(args: Uint8Array): Promise<Uint8Array>;
  abstract homeStats(args: Uint8Array): Promise<Uint8Array>;
  abstract search(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract duplicate(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case ProjectMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.allForPermissions: {
        const body = await this.allForPermissions(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.homeStats: {
        const body = await this.homeStats(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.search: {
        const body = await this.search(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ProjectMethod.duplicate: {
        const body = await this.duplicate(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


