// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: redis.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Redis service (stable wire ids). */
export const RedisMethod = {
  create: 1,
  one: 2,
  start: 3,
  reload: 4,
  stop: 5,
  saveExternalPort: 6,
  deploy: 7,
  deployWithLogs: 8,
  changeStatus: 9,
  remove: 10,
  saveEnvironment: 11,
  update: 12,
  changePassword: 13,
  move: 14,
  rebuild: 15,
  search: 16,
  readLogs: 17,
} as const;

/** Typed RPC client for the Redis service over a ZAP call channel. */
export interface RedisChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class RedisClient {
  constructor(private readonly channel: RedisChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async start(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.start,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.start: status ${resp.status}`);
    }
    return resp.body;
  }

  async reload(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.reload,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.reload: status ${resp.status}`);
    }
    return resp.body;
  }

  async stop(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.stop,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.stop: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveExternalPort(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.saveExternalPort,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.saveExternalPort: status ${resp.status}`);
    }
    return resp.body;
  }

  async deploy(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.deploy,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.deploy: status ${resp.status}`);
    }
    return resp.body;
  }

  async deployWithLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.deployWithLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.deployWithLogs: status ${resp.status}`);
    }
    return resp.body;
  }

  async changeStatus(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.changeStatus,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.changeStatus: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveEnvironment(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.saveEnvironment,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.saveEnvironment: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async changePassword(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.changePassword,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.changePassword: status ${resp.status}`);
    }
    return resp.body;
  }

  async move(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.move,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.move: status ${resp.status}`);
    }
    return resp.body;
  }

  async rebuild(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.rebuild,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.rebuild: status ${resp.status}`);
    }
    return resp.body;
  }

  async search(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.search,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.search: status ${resp.status}`);
    }
    return resp.body;
  }

  async readLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RedisMethod.readLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Redis.readLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Redis service. Subclass and implement each method. */
export abstract class RedisServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract start(args: Uint8Array): Promise<Uint8Array>;
  abstract reload(args: Uint8Array): Promise<Uint8Array>;
  abstract stop(args: Uint8Array): Promise<Uint8Array>;
  abstract saveExternalPort(args: Uint8Array): Promise<Uint8Array>;
  abstract deploy(args: Uint8Array): Promise<Uint8Array>;
  abstract deployWithLogs(args: Uint8Array): Promise<Uint8Array>;
  abstract changeStatus(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract saveEnvironment(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract changePassword(args: Uint8Array): Promise<Uint8Array>;
  abstract move(args: Uint8Array): Promise<Uint8Array>;
  abstract rebuild(args: Uint8Array): Promise<Uint8Array>;
  abstract search(args: Uint8Array): Promise<Uint8Array>;
  abstract readLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case RedisMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.start: {
        const body = await this.start(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.reload: {
        const body = await this.reload(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.stop: {
        const body = await this.stop(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.saveExternalPort: {
        const body = await this.saveExternalPort(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.deploy: {
        const body = await this.deploy(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.deployWithLogs: {
        const body = await this.deployWithLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.changeStatus: {
        const body = await this.changeStatus(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.saveEnvironment: {
        const body = await this.saveEnvironment(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.changePassword: {
        const body = await this.changePassword(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.move: {
        const body = await this.move(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.rebuild: {
        const body = await this.rebuild(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.search: {
        const body = await this.search(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RedisMethod.readLogs: {
        const body = await this.readLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


