// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: rollback.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Rollback service (stable wire ids). */
export const RollbackMethod = {
  delete: 1,
  rollback: 2,
} as const;

/** Typed RPC client for the Rollback service over a ZAP call channel. */
export interface RollbackChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class RollbackClient {
  constructor(private readonly channel: RollbackChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RollbackMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Rollback.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async rollback(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: RollbackMethod.rollback,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Rollback.rollback: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Rollback service. Subclass and implement each method. */
export abstract class RollbackServer {
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract rollback(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case RollbackMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case RollbackMethod.rollback: {
        const body = await this.rollback(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


