// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: schedule.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Schedule service (stable wire ids). */
export const ScheduleMethod = {
  create: 1,
  update: 2,
  delete: 3,
  list: 4,
  one: 5,
  runManually: 6,
} as const;

/** Typed RPC client for the Schedule service over a ZAP call channel. */
export interface ScheduleChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class ScheduleClient {
  constructor(private readonly channel: ScheduleChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ScheduleMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Schedule.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ScheduleMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Schedule.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ScheduleMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Schedule.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async list(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ScheduleMethod.list,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Schedule.list: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ScheduleMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Schedule.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async runManually(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: ScheduleMethod.runManually,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Schedule.runManually: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Schedule service. Subclass and implement each method. */
export abstract class ScheduleServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract list(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract runManually(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case ScheduleMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ScheduleMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ScheduleMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ScheduleMethod.list: {
        const body = await this.list(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ScheduleMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case ScheduleMethod.runManually: {
        const body = await this.runManually(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


