// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: settings.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Settings service (stable wire ids). */
export const SettingsMethod = {
  getWebServerSettings: 1,
  reloadServer: 2,
  cleanRedis: 3,
  reloadRedis: 4,
  cleanAllDeploymentQueue: 5,
  reloadTraefik: 6,
  toggleDashboard: 7,
  cleanUnusedImages: 8,
  cleanUnusedVolumes: 9,
  cleanStoppedContainers: 10,
  cleanDockerBuilder: 11,
  cleanDockerPrune: 12,
  cleanAll: 13,
  cleanMonitoring: 14,
  getDockerDiskUsage: 15,
  saveSSHPrivateKey: 16,
  assignDomainServer: 17,
  cleanSSHPrivateKey: 18,
  updateDockerCleanup: 19,
  updateRemoteServersOnly: 20,
  updateEnforceSSO: 21,
  readTraefikConfig: 22,
  updateTraefikConfig: 23,
  readWebServerTraefikConfig: 24,
  updateWebServerTraefikConfig: 25,
  readMiddlewareTraefikConfig: 26,
  updateMiddlewareTraefikConfig: 27,
  getUpdateData: 28,
  updateServer: 29,
  getHanzoVersion: 30,
  getReleaseTag: 31,
  readDirectories: 32,
  updateTraefikFile: 33,
  readTraefikFile: 34,
  getIp: 35,
  updateServerIp: 36,
  getOpenApiDocument: 37,
  readTraefikEnv: 38,
  writeTraefikEnv: 39,
  haveTraefikDashboardPortEnabled: 40,
  readStatsLogs: 41,
  readStats: 42,
  haveActivateRequests: 43,
  toggleRequests: 44,
  isCloud: 45,
  isUserSubscribed: 46,
  health: 47,
  checkInfrastructureHealth: 48,
  setupGPU: 49,
  checkGPUStatus: 50,
  updateTraefikPorts: 51,
  getTraefikPorts: 52,
  updateLogCleanup: 53,
  getLogCleanupStatus: 54,
  getHanzoCloudIps: 55,
} as const;

/** Typed RPC client for the Settings service over a ZAP call channel. */
export interface SettingsChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class SettingsClient {
  constructor(private readonly channel: SettingsChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async getWebServerSettings(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getWebServerSettings,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getWebServerSettings: status ${resp.status}`);
    }
    return resp.body;
  }

  async reloadServer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.reloadServer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.reloadServer: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanRedis(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanRedis,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanRedis: status ${resp.status}`);
    }
    return resp.body;
  }

  async reloadRedis(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.reloadRedis,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.reloadRedis: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanAllDeploymentQueue(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanAllDeploymentQueue,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanAllDeploymentQueue: status ${resp.status}`);
    }
    return resp.body;
  }

  async reloadTraefik(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.reloadTraefik,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.reloadTraefik: status ${resp.status}`);
    }
    return resp.body;
  }

  async toggleDashboard(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.toggleDashboard,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.toggleDashboard: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanUnusedImages(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanUnusedImages,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanUnusedImages: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanUnusedVolumes(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanUnusedVolumes,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanUnusedVolumes: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanStoppedContainers(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanStoppedContainers,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanStoppedContainers: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanDockerBuilder(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanDockerBuilder,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanDockerBuilder: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanDockerPrune(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanDockerPrune,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanDockerPrune: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanAll(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanAll,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanAll: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanMonitoring(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanMonitoring,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanMonitoring: status ${resp.status}`);
    }
    return resp.body;
  }

  async getDockerDiskUsage(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getDockerDiskUsage,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getDockerDiskUsage: status ${resp.status}`);
    }
    return resp.body;
  }

  async saveSSHPrivateKey(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.saveSSHPrivateKey,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.saveSSHPrivateKey: status ${resp.status}`);
    }
    return resp.body;
  }

  async assignDomainServer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.assignDomainServer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.assignDomainServer: status ${resp.status}`);
    }
    return resp.body;
  }

  async cleanSSHPrivateKey(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.cleanSSHPrivateKey,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.cleanSSHPrivateKey: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateDockerCleanup(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateDockerCleanup,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateDockerCleanup: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateRemoteServersOnly(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateRemoteServersOnly,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateRemoteServersOnly: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateEnforceSSO(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateEnforceSSO,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateEnforceSSO: status ${resp.status}`);
    }
    return resp.body;
  }

  async readTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async readWebServerTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readWebServerTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readWebServerTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateWebServerTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateWebServerTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateWebServerTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async readMiddlewareTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readMiddlewareTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readMiddlewareTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateMiddlewareTraefikConfig(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateMiddlewareTraefikConfig,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateMiddlewareTraefikConfig: status ${resp.status}`);
    }
    return resp.body;
  }

  async getUpdateData(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getUpdateData,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getUpdateData: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateServer(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateServer,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateServer: status ${resp.status}`);
    }
    return resp.body;
  }

  async getHanzoVersion(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getHanzoVersion,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getHanzoVersion: status ${resp.status}`);
    }
    return resp.body;
  }

  async getReleaseTag(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getReleaseTag,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getReleaseTag: status ${resp.status}`);
    }
    return resp.body;
  }

  async readDirectories(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readDirectories,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readDirectories: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateTraefikFile(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateTraefikFile,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateTraefikFile: status ${resp.status}`);
    }
    return resp.body;
  }

  async readTraefikFile(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readTraefikFile,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readTraefikFile: status ${resp.status}`);
    }
    return resp.body;
  }

  async getIp(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getIp,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getIp: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateServerIp(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateServerIp,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateServerIp: status ${resp.status}`);
    }
    return resp.body;
  }

  async getOpenApiDocument(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getOpenApiDocument,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getOpenApiDocument: status ${resp.status}`);
    }
    return resp.body;
  }

  async readTraefikEnv(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readTraefikEnv,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readTraefikEnv: status ${resp.status}`);
    }
    return resp.body;
  }

  async writeTraefikEnv(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.writeTraefikEnv,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.writeTraefikEnv: status ${resp.status}`);
    }
    return resp.body;
  }

  async haveTraefikDashboardPortEnabled(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.haveTraefikDashboardPortEnabled,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.haveTraefikDashboardPortEnabled: status ${resp.status}`);
    }
    return resp.body;
  }

  async readStatsLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readStatsLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readStatsLogs: status ${resp.status}`);
    }
    return resp.body;
  }

  async readStats(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.readStats,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.readStats: status ${resp.status}`);
    }
    return resp.body;
  }

  async haveActivateRequests(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.haveActivateRequests,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.haveActivateRequests: status ${resp.status}`);
    }
    return resp.body;
  }

  async toggleRequests(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.toggleRequests,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.toggleRequests: status ${resp.status}`);
    }
    return resp.body;
  }

  async isCloud(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.isCloud,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.isCloud: status ${resp.status}`);
    }
    return resp.body;
  }

  async isUserSubscribed(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.isUserSubscribed,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.isUserSubscribed: status ${resp.status}`);
    }
    return resp.body;
  }

  async health(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.health,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.health: status ${resp.status}`);
    }
    return resp.body;
  }

  async checkInfrastructureHealth(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.checkInfrastructureHealth,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.checkInfrastructureHealth: status ${resp.status}`);
    }
    return resp.body;
  }

  async setupGPU(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.setupGPU,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.setupGPU: status ${resp.status}`);
    }
    return resp.body;
  }

  async checkGPUStatus(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.checkGPUStatus,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.checkGPUStatus: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateTraefikPorts(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateTraefikPorts,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateTraefikPorts: status ${resp.status}`);
    }
    return resp.body;
  }

  async getTraefikPorts(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getTraefikPorts,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getTraefikPorts: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateLogCleanup(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.updateLogCleanup,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.updateLogCleanup: status ${resp.status}`);
    }
    return resp.body;
  }

  async getLogCleanupStatus(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getLogCleanupStatus,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getLogCleanupStatus: status ${resp.status}`);
    }
    return resp.body;
  }

  async getHanzoCloudIps(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SettingsMethod.getHanzoCloudIps,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Settings.getHanzoCloudIps: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Settings service. Subclass and implement each method. */
export abstract class SettingsServer {
  abstract getWebServerSettings(args: Uint8Array): Promise<Uint8Array>;
  abstract reloadServer(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanRedis(args: Uint8Array): Promise<Uint8Array>;
  abstract reloadRedis(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanAllDeploymentQueue(args: Uint8Array): Promise<Uint8Array>;
  abstract reloadTraefik(args: Uint8Array): Promise<Uint8Array>;
  abstract toggleDashboard(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanUnusedImages(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanUnusedVolumes(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanStoppedContainers(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanDockerBuilder(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanDockerPrune(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanAll(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanMonitoring(args: Uint8Array): Promise<Uint8Array>;
  abstract getDockerDiskUsage(args: Uint8Array): Promise<Uint8Array>;
  abstract saveSSHPrivateKey(args: Uint8Array): Promise<Uint8Array>;
  abstract assignDomainServer(args: Uint8Array): Promise<Uint8Array>;
  abstract cleanSSHPrivateKey(args: Uint8Array): Promise<Uint8Array>;
  abstract updateDockerCleanup(args: Uint8Array): Promise<Uint8Array>;
  abstract updateRemoteServersOnly(args: Uint8Array): Promise<Uint8Array>;
  abstract updateEnforceSSO(args: Uint8Array): Promise<Uint8Array>;
  abstract readTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract updateTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract readWebServerTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract updateWebServerTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract readMiddlewareTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract updateMiddlewareTraefikConfig(args: Uint8Array): Promise<Uint8Array>;
  abstract getUpdateData(args: Uint8Array): Promise<Uint8Array>;
  abstract updateServer(args: Uint8Array): Promise<Uint8Array>;
  abstract getHanzoVersion(args: Uint8Array): Promise<Uint8Array>;
  abstract getReleaseTag(args: Uint8Array): Promise<Uint8Array>;
  abstract readDirectories(args: Uint8Array): Promise<Uint8Array>;
  abstract updateTraefikFile(args: Uint8Array): Promise<Uint8Array>;
  abstract readTraefikFile(args: Uint8Array): Promise<Uint8Array>;
  abstract getIp(args: Uint8Array): Promise<Uint8Array>;
  abstract updateServerIp(args: Uint8Array): Promise<Uint8Array>;
  abstract getOpenApiDocument(args: Uint8Array): Promise<Uint8Array>;
  abstract readTraefikEnv(args: Uint8Array): Promise<Uint8Array>;
  abstract writeTraefikEnv(args: Uint8Array): Promise<Uint8Array>;
  abstract haveTraefikDashboardPortEnabled(args: Uint8Array): Promise<Uint8Array>;
  abstract readStatsLogs(args: Uint8Array): Promise<Uint8Array>;
  abstract readStats(args: Uint8Array): Promise<Uint8Array>;
  abstract haveActivateRequests(args: Uint8Array): Promise<Uint8Array>;
  abstract toggleRequests(args: Uint8Array): Promise<Uint8Array>;
  abstract isCloud(args: Uint8Array): Promise<Uint8Array>;
  abstract isUserSubscribed(args: Uint8Array): Promise<Uint8Array>;
  abstract health(args: Uint8Array): Promise<Uint8Array>;
  abstract checkInfrastructureHealth(args: Uint8Array): Promise<Uint8Array>;
  abstract setupGPU(args: Uint8Array): Promise<Uint8Array>;
  abstract checkGPUStatus(args: Uint8Array): Promise<Uint8Array>;
  abstract updateTraefikPorts(args: Uint8Array): Promise<Uint8Array>;
  abstract getTraefikPorts(args: Uint8Array): Promise<Uint8Array>;
  abstract updateLogCleanup(args: Uint8Array): Promise<Uint8Array>;
  abstract getLogCleanupStatus(args: Uint8Array): Promise<Uint8Array>;
  abstract getHanzoCloudIps(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case SettingsMethod.getWebServerSettings: {
        const body = await this.getWebServerSettings(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.reloadServer: {
        const body = await this.reloadServer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanRedis: {
        const body = await this.cleanRedis(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.reloadRedis: {
        const body = await this.reloadRedis(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanAllDeploymentQueue: {
        const body = await this.cleanAllDeploymentQueue(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.reloadTraefik: {
        const body = await this.reloadTraefik(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.toggleDashboard: {
        const body = await this.toggleDashboard(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanUnusedImages: {
        const body = await this.cleanUnusedImages(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanUnusedVolumes: {
        const body = await this.cleanUnusedVolumes(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanStoppedContainers: {
        const body = await this.cleanStoppedContainers(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanDockerBuilder: {
        const body = await this.cleanDockerBuilder(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanDockerPrune: {
        const body = await this.cleanDockerPrune(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanAll: {
        const body = await this.cleanAll(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanMonitoring: {
        const body = await this.cleanMonitoring(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getDockerDiskUsage: {
        const body = await this.getDockerDiskUsage(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.saveSSHPrivateKey: {
        const body = await this.saveSSHPrivateKey(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.assignDomainServer: {
        const body = await this.assignDomainServer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.cleanSSHPrivateKey: {
        const body = await this.cleanSSHPrivateKey(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateDockerCleanup: {
        const body = await this.updateDockerCleanup(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateRemoteServersOnly: {
        const body = await this.updateRemoteServersOnly(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateEnforceSSO: {
        const body = await this.updateEnforceSSO(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readTraefikConfig: {
        const body = await this.readTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateTraefikConfig: {
        const body = await this.updateTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readWebServerTraefikConfig: {
        const body = await this.readWebServerTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateWebServerTraefikConfig: {
        const body = await this.updateWebServerTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readMiddlewareTraefikConfig: {
        const body = await this.readMiddlewareTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateMiddlewareTraefikConfig: {
        const body = await this.updateMiddlewareTraefikConfig(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getUpdateData: {
        const body = await this.getUpdateData(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateServer: {
        const body = await this.updateServer(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getHanzoVersion: {
        const body = await this.getHanzoVersion(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getReleaseTag: {
        const body = await this.getReleaseTag(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readDirectories: {
        const body = await this.readDirectories(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateTraefikFile: {
        const body = await this.updateTraefikFile(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readTraefikFile: {
        const body = await this.readTraefikFile(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getIp: {
        const body = await this.getIp(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateServerIp: {
        const body = await this.updateServerIp(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getOpenApiDocument: {
        const body = await this.getOpenApiDocument(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readTraefikEnv: {
        const body = await this.readTraefikEnv(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.writeTraefikEnv: {
        const body = await this.writeTraefikEnv(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.haveTraefikDashboardPortEnabled: {
        const body = await this.haveTraefikDashboardPortEnabled(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readStatsLogs: {
        const body = await this.readStatsLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.readStats: {
        const body = await this.readStats(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.haveActivateRequests: {
        const body = await this.haveActivateRequests(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.toggleRequests: {
        const body = await this.toggleRequests(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.isCloud: {
        const body = await this.isCloud(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.isUserSubscribed: {
        const body = await this.isUserSubscribed(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.health: {
        const body = await this.health(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.checkInfrastructureHealth: {
        const body = await this.checkInfrastructureHealth(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.setupGPU: {
        const body = await this.setupGPU(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.checkGPUStatus: {
        const body = await this.checkGPUStatus(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateTraefikPorts: {
        const body = await this.updateTraefikPorts(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getTraefikPorts: {
        const body = await this.getTraefikPorts(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.updateLogCleanup: {
        const body = await this.updateLogCleanup(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getLogCleanupStatus: {
        const body = await this.getLogCleanupStatus(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SettingsMethod.getHanzoCloudIps: {
        const body = await this.getHanzoCloudIps(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


