// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: ssh-key.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the SshKey service (stable wire ids). */
export const SshKeyMethod = {
  create: 1,
  remove: 2,
  one: 3,
  all: 4,
  allForApps: 5,
  generate: 6,
  update: 7,
} as const;

/** Typed RPC client for the SshKey service over a ZAP call channel. */
export interface SshKeyChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class SshKeyClient {
  constructor(private readonly channel: SshKeyChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SshKeyMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`SshKey.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SshKeyMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`SshKey.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SshKeyMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`SshKey.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SshKeyMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`SshKey.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async allForApps(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SshKeyMethod.allForApps,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`SshKey.allForApps: status ${resp.status}`);
    }
    return resp.body;
  }

  async generate(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SshKeyMethod.generate,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`SshKey.generate: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SshKeyMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`SshKey.update: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the SshKey service. Subclass and implement each method. */
export abstract class SshKeyServer {
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract allForApps(args: Uint8Array): Promise<Uint8Array>;
  abstract generate(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case SshKeyMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SshKeyMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SshKeyMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SshKeyMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SshKeyMethod.allForApps: {
        const body = await this.allForApps(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SshKeyMethod.generate: {
        const body = await this.generate(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SshKeyMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


