// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: sso.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Sso service (stable wire ids). */
export const SsoMethod = {
  showSignInWithSSO: 1,
  enforceSSO: 2,
  listProviders: 3,
  getTrustedOrigins: 4,
  one: 5,
  update: 6,
  deleteProvider: 7,
  register: 8,
  addTrustedOrigin: 9,
  removeTrustedOrigin: 10,
  updateTrustedOrigin: 11,
} as const;

/** Typed RPC client for the Sso service over a ZAP call channel. */
export interface SsoChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class SsoClient {
  constructor(private readonly channel: SsoChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async showSignInWithSSO(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.showSignInWithSSO,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.showSignInWithSSO: status ${resp.status}`);
    }
    return resp.body;
  }

  async enforceSSO(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.enforceSSO,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.enforceSSO: status ${resp.status}`);
    }
    return resp.body;
  }

  async listProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.listProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.listProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async getTrustedOrigins(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.getTrustedOrigins,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.getTrustedOrigins: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteProvider(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.deleteProvider,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.deleteProvider: status ${resp.status}`);
    }
    return resp.body;
  }

  async register(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.register,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.register: status ${resp.status}`);
    }
    return resp.body;
  }

  async addTrustedOrigin(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.addTrustedOrigin,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.addTrustedOrigin: status ${resp.status}`);
    }
    return resp.body;
  }

  async removeTrustedOrigin(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.removeTrustedOrigin,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.removeTrustedOrigin: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateTrustedOrigin(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SsoMethod.updateTrustedOrigin,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Sso.updateTrustedOrigin: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Sso service. Subclass and implement each method. */
export abstract class SsoServer {
  abstract showSignInWithSSO(args: Uint8Array): Promise<Uint8Array>;
  abstract enforceSSO(args: Uint8Array): Promise<Uint8Array>;
  abstract listProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract getTrustedOrigins(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract deleteProvider(args: Uint8Array): Promise<Uint8Array>;
  abstract register(args: Uint8Array): Promise<Uint8Array>;
  abstract addTrustedOrigin(args: Uint8Array): Promise<Uint8Array>;
  abstract removeTrustedOrigin(args: Uint8Array): Promise<Uint8Array>;
  abstract updateTrustedOrigin(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case SsoMethod.showSignInWithSSO: {
        const body = await this.showSignInWithSSO(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.enforceSSO: {
        const body = await this.enforceSSO(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.listProviders: {
        const body = await this.listProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.getTrustedOrigins: {
        const body = await this.getTrustedOrigins(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.deleteProvider: {
        const body = await this.deleteProvider(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.register: {
        const body = await this.register(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.addTrustedOrigin: {
        const body = await this.addTrustedOrigin(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.removeTrustedOrigin: {
        const body = await this.removeTrustedOrigin(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SsoMethod.updateTrustedOrigin: {
        const body = await this.updateTrustedOrigin(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


