// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: stripe.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Stripe service (stable wire ids). */
export const StripeMethod = {
  getCurrentPlan: 1,
  getProducts: 2,
  createCheckoutSession: 3,
  createCustomerPortalSession: 4,
  upgradeSubscription: 5,
  canCreateMoreServers: 6,
  getInvoices: 7,
} as const;

/** Typed RPC client for the Stripe service over a ZAP call channel. */
export interface StripeChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class StripeClient {
  constructor(private readonly channel: StripeChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async getCurrentPlan(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: StripeMethod.getCurrentPlan,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Stripe.getCurrentPlan: status ${resp.status}`);
    }
    return resp.body;
  }

  async getProducts(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: StripeMethod.getProducts,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Stripe.getProducts: status ${resp.status}`);
    }
    return resp.body;
  }

  async createCheckoutSession(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: StripeMethod.createCheckoutSession,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Stripe.createCheckoutSession: status ${resp.status}`);
    }
    return resp.body;
  }

  async createCustomerPortalSession(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: StripeMethod.createCustomerPortalSession,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Stripe.createCustomerPortalSession: status ${resp.status}`);
    }
    return resp.body;
  }

  async upgradeSubscription(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: StripeMethod.upgradeSubscription,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Stripe.upgradeSubscription: status ${resp.status}`);
    }
    return resp.body;
  }

  async canCreateMoreServers(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: StripeMethod.canCreateMoreServers,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Stripe.canCreateMoreServers: status ${resp.status}`);
    }
    return resp.body;
  }

  async getInvoices(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: StripeMethod.getInvoices,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Stripe.getInvoices: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Stripe service. Subclass and implement each method. */
export abstract class StripeServer {
  abstract getCurrentPlan(args: Uint8Array): Promise<Uint8Array>;
  abstract getProducts(args: Uint8Array): Promise<Uint8Array>;
  abstract createCheckoutSession(args: Uint8Array): Promise<Uint8Array>;
  abstract createCustomerPortalSession(args: Uint8Array): Promise<Uint8Array>;
  abstract upgradeSubscription(args: Uint8Array): Promise<Uint8Array>;
  abstract canCreateMoreServers(args: Uint8Array): Promise<Uint8Array>;
  abstract getInvoices(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case StripeMethod.getCurrentPlan: {
        const body = await this.getCurrentPlan(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case StripeMethod.getProducts: {
        const body = await this.getProducts(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case StripeMethod.createCheckoutSession: {
        const body = await this.createCheckoutSession(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case StripeMethod.createCustomerPortalSession: {
        const body = await this.createCustomerPortalSession(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case StripeMethod.upgradeSubscription: {
        const body = await this.upgradeSubscription(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case StripeMethod.canCreateMoreServers: {
        const body = await this.canCreateMoreServers(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case StripeMethod.getInvoices: {
        const body = await this.getInvoices(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


