// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: swarm.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Swarm service (stable wire ids). */
export const SwarmMethod = {
  getNodes: 1,
  getNodeInfo: 2,
  getNodeApps: 3,
  getAppInfos: 4,
  getContainerStats: 5,
} as const;

/** Typed RPC client for the Swarm service over a ZAP call channel. */
export interface SwarmChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class SwarmClient {
  constructor(private readonly channel: SwarmChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async getNodes(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SwarmMethod.getNodes,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Swarm.getNodes: status ${resp.status}`);
    }
    return resp.body;
  }

  async getNodeInfo(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SwarmMethod.getNodeInfo,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Swarm.getNodeInfo: status ${resp.status}`);
    }
    return resp.body;
  }

  async getNodeApps(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SwarmMethod.getNodeApps,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Swarm.getNodeApps: status ${resp.status}`);
    }
    return resp.body;
  }

  async getAppInfos(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SwarmMethod.getAppInfos,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Swarm.getAppInfos: status ${resp.status}`);
    }
    return resp.body;
  }

  async getContainerStats(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: SwarmMethod.getContainerStats,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Swarm.getContainerStats: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Swarm service. Subclass and implement each method. */
export abstract class SwarmServer {
  abstract getNodes(args: Uint8Array): Promise<Uint8Array>;
  abstract getNodeInfo(args: Uint8Array): Promise<Uint8Array>;
  abstract getNodeApps(args: Uint8Array): Promise<Uint8Array>;
  abstract getAppInfos(args: Uint8Array): Promise<Uint8Array>;
  abstract getContainerStats(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case SwarmMethod.getNodes: {
        const body = await this.getNodes(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SwarmMethod.getNodeInfo: {
        const body = await this.getNodeInfo(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SwarmMethod.getNodeApps: {
        const body = await this.getNodeApps(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SwarmMethod.getAppInfos: {
        const body = await this.getAppInfos(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case SwarmMethod.getContainerStats: {
        const body = await this.getContainerStats(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


