// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: user.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the User service (stable wire ids). */
export const UserMethod = {
  all: 1,
  one: 2,
  session: 3,
  get: 4,
  getPermissions: 5,
  haveRootAccess: 6,
  getBackups: 7,
  getServerMetrics: 8,
  update: 9,
  getUserByToken: 10,
  getMetricsToken: 11,
  remove: 12,
  assignPermissions: 13,
  getInvitations: 14,
  getContainerMetrics: 15,
  generateToken: 16,
  deleteApiKey: 17,
  createApiKey: 18,
  checkUserOrganizations: 19,
  createUserWithCredentials: 20,
  sendInvitation: 21,
  getBookmarkedTemplates: 22,
  toggleTemplateBookmark: 23,
} as const;

/** Typed RPC client for the User service over a ZAP call channel. */
export interface UserChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class UserClient {
  constructor(private readonly channel: UserChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async all(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.all,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.all: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async session(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.session,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.session: status ${resp.status}`);
    }
    return resp.body;
  }

  async get(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.get,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.get: status ${resp.status}`);
    }
    return resp.body;
  }

  async getPermissions(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getPermissions,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getPermissions: status ${resp.status}`);
    }
    return resp.body;
  }

  async haveRootAccess(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.haveRootAccess,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.haveRootAccess: status ${resp.status}`);
    }
    return resp.body;
  }

  async getBackups(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getBackups,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getBackups: status ${resp.status}`);
    }
    return resp.body;
  }

  async getServerMetrics(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getServerMetrics,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getServerMetrics: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async getUserByToken(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getUserByToken,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getUserByToken: status ${resp.status}`);
    }
    return resp.body;
  }

  async getMetricsToken(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getMetricsToken,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getMetricsToken: status ${resp.status}`);
    }
    return resp.body;
  }

  async remove(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.remove,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.remove: status ${resp.status}`);
    }
    return resp.body;
  }

  async assignPermissions(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.assignPermissions,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.assignPermissions: status ${resp.status}`);
    }
    return resp.body;
  }

  async getInvitations(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getInvitations,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getInvitations: status ${resp.status}`);
    }
    return resp.body;
  }

  async getContainerMetrics(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getContainerMetrics,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getContainerMetrics: status ${resp.status}`);
    }
    return resp.body;
  }

  async generateToken(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.generateToken,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.generateToken: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteApiKey(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.deleteApiKey,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.deleteApiKey: status ${resp.status}`);
    }
    return resp.body;
  }

  async createApiKey(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.createApiKey,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.createApiKey: status ${resp.status}`);
    }
    return resp.body;
  }

  async checkUserOrganizations(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.checkUserOrganizations,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.checkUserOrganizations: status ${resp.status}`);
    }
    return resp.body;
  }

  async createUserWithCredentials(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.createUserWithCredentials,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.createUserWithCredentials: status ${resp.status}`);
    }
    return resp.body;
  }

  async sendInvitation(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.sendInvitation,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.sendInvitation: status ${resp.status}`);
    }
    return resp.body;
  }

  async getBookmarkedTemplates(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.getBookmarkedTemplates,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.getBookmarkedTemplates: status ${resp.status}`);
    }
    return resp.body;
  }

  async toggleTemplateBookmark(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: UserMethod.toggleTemplateBookmark,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`User.toggleTemplateBookmark: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the User service. Subclass and implement each method. */
export abstract class UserServer {
  abstract all(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract session(args: Uint8Array): Promise<Uint8Array>;
  abstract get(args: Uint8Array): Promise<Uint8Array>;
  abstract getPermissions(args: Uint8Array): Promise<Uint8Array>;
  abstract haveRootAccess(args: Uint8Array): Promise<Uint8Array>;
  abstract getBackups(args: Uint8Array): Promise<Uint8Array>;
  abstract getServerMetrics(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract getUserByToken(args: Uint8Array): Promise<Uint8Array>;
  abstract getMetricsToken(args: Uint8Array): Promise<Uint8Array>;
  abstract remove(args: Uint8Array): Promise<Uint8Array>;
  abstract assignPermissions(args: Uint8Array): Promise<Uint8Array>;
  abstract getInvitations(args: Uint8Array): Promise<Uint8Array>;
  abstract getContainerMetrics(args: Uint8Array): Promise<Uint8Array>;
  abstract generateToken(args: Uint8Array): Promise<Uint8Array>;
  abstract deleteApiKey(args: Uint8Array): Promise<Uint8Array>;
  abstract createApiKey(args: Uint8Array): Promise<Uint8Array>;
  abstract checkUserOrganizations(args: Uint8Array): Promise<Uint8Array>;
  abstract createUserWithCredentials(args: Uint8Array): Promise<Uint8Array>;
  abstract sendInvitation(args: Uint8Array): Promise<Uint8Array>;
  abstract getBookmarkedTemplates(args: Uint8Array): Promise<Uint8Array>;
  abstract toggleTemplateBookmark(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case UserMethod.all: {
        const body = await this.all(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.session: {
        const body = await this.session(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.get: {
        const body = await this.get(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getPermissions: {
        const body = await this.getPermissions(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.haveRootAccess: {
        const body = await this.haveRootAccess(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getBackups: {
        const body = await this.getBackups(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getServerMetrics: {
        const body = await this.getServerMetrics(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getUserByToken: {
        const body = await this.getUserByToken(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getMetricsToken: {
        const body = await this.getMetricsToken(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.remove: {
        const body = await this.remove(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.assignPermissions: {
        const body = await this.assignPermissions(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getInvitations: {
        const body = await this.getInvitations(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getContainerMetrics: {
        const body = await this.getContainerMetrics(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.generateToken: {
        const body = await this.generateToken(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.deleteApiKey: {
        const body = await this.deleteApiKey(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.createApiKey: {
        const body = await this.createApiKey(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.checkUserOrganizations: {
        const body = await this.checkUserOrganizations(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.createUserWithCredentials: {
        const body = await this.createUserWithCredentials(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.sendInvitation: {
        const body = await this.sendInvitation(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.getBookmarkedTemplates: {
        const body = await this.getBookmarkedTemplates(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case UserMethod.toggleTemplateBookmark: {
        const body = await this.toggleTemplateBookmark(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


