// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: visor.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Visor service (stable wire ids). */
export const VisorMethod = {
  listMachines: 1,
  getMachine: 2,
  createMachine: 3,
  updateMachine: 4,
  deleteMachine: 5,
  listProviders: 6,
  listPlans: 7,
  listNodePools: 8,
  listVolumes: 9,
  createVolume: 10,
  deleteVolume: 11,
} as const;

/** Typed RPC client for the Visor service over a ZAP call channel. */
export interface VisorChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class VisorClient {
  constructor(private readonly channel: VisorChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async listMachines(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.listMachines,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.listMachines: status ${resp.status}`);
    }
    return resp.body;
  }

  async getMachine(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.getMachine,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.getMachine: status ${resp.status}`);
    }
    return resp.body;
  }

  async createMachine(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.createMachine,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.createMachine: status ${resp.status}`);
    }
    return resp.body;
  }

  async updateMachine(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.updateMachine,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.updateMachine: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteMachine(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.deleteMachine,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.deleteMachine: status ${resp.status}`);
    }
    return resp.body;
  }

  async listProviders(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.listProviders,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.listProviders: status ${resp.status}`);
    }
    return resp.body;
  }

  async listPlans(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.listPlans,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.listPlans: status ${resp.status}`);
    }
    return resp.body;
  }

  async listNodePools(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.listNodePools,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.listNodePools: status ${resp.status}`);
    }
    return resp.body;
  }

  async listVolumes(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.listVolumes,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.listVolumes: status ${resp.status}`);
    }
    return resp.body;
  }

  async createVolume(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.createVolume,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.createVolume: status ${resp.status}`);
    }
    return resp.body;
  }

  async deleteVolume(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VisorMethod.deleteVolume,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Visor.deleteVolume: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Visor service. Subclass and implement each method. */
export abstract class VisorServer {
  abstract listMachines(args: Uint8Array): Promise<Uint8Array>;
  abstract getMachine(args: Uint8Array): Promise<Uint8Array>;
  abstract createMachine(args: Uint8Array): Promise<Uint8Array>;
  abstract updateMachine(args: Uint8Array): Promise<Uint8Array>;
  abstract deleteMachine(args: Uint8Array): Promise<Uint8Array>;
  abstract listProviders(args: Uint8Array): Promise<Uint8Array>;
  abstract listPlans(args: Uint8Array): Promise<Uint8Array>;
  abstract listNodePools(args: Uint8Array): Promise<Uint8Array>;
  abstract listVolumes(args: Uint8Array): Promise<Uint8Array>;
  abstract createVolume(args: Uint8Array): Promise<Uint8Array>;
  abstract deleteVolume(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case VisorMethod.listMachines: {
        const body = await this.listMachines(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.getMachine: {
        const body = await this.getMachine(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.createMachine: {
        const body = await this.createMachine(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.updateMachine: {
        const body = await this.updateMachine(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.deleteMachine: {
        const body = await this.deleteMachine(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.listProviders: {
        const body = await this.listProviders(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.listPlans: {
        const body = await this.listPlans(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.listNodePools: {
        const body = await this.listNodePools(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.listVolumes: {
        const body = await this.listVolumes(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.createVolume: {
        const body = await this.createVolume(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VisorMethod.deleteVolume: {
        const body = await this.deleteVolume(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


