// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: volume-backups.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the VolumeBackups service (stable wire ids). */
export const VolumeBackupsMethod = {
  list: 1,
  create: 2,
  one: 3,
  delete: 4,
  update: 5,
  runManually: 6,
  restoreVolumeBackupWithLogs: 7,
} as const;

/** Typed RPC client for the VolumeBackups service over a ZAP call channel. */
export interface VolumeBackupsChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class VolumeBackupsClient {
  constructor(private readonly channel: VolumeBackupsChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async list(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VolumeBackupsMethod.list,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`VolumeBackups.list: status ${resp.status}`);
    }
    return resp.body;
  }

  async create(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VolumeBackupsMethod.create,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`VolumeBackups.create: status ${resp.status}`);
    }
    return resp.body;
  }

  async one(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VolumeBackupsMethod.one,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`VolumeBackups.one: status ${resp.status}`);
    }
    return resp.body;
  }

  async delete(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VolumeBackupsMethod.delete,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`VolumeBackups.delete: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VolumeBackupsMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`VolumeBackups.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async runManually(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VolumeBackupsMethod.runManually,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`VolumeBackups.runManually: status ${resp.status}`);
    }
    return resp.body;
  }

  async restoreVolumeBackupWithLogs(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: VolumeBackupsMethod.restoreVolumeBackupWithLogs,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`VolumeBackups.restoreVolumeBackupWithLogs: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the VolumeBackups service. Subclass and implement each method. */
export abstract class VolumeBackupsServer {
  abstract list(args: Uint8Array): Promise<Uint8Array>;
  abstract create(args: Uint8Array): Promise<Uint8Array>;
  abstract one(args: Uint8Array): Promise<Uint8Array>;
  abstract delete(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract runManually(args: Uint8Array): Promise<Uint8Array>;
  abstract restoreVolumeBackupWithLogs(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case VolumeBackupsMethod.list: {
        const body = await this.list(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VolumeBackupsMethod.create: {
        const body = await this.create(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VolumeBackupsMethod.one: {
        const body = await this.one(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VolumeBackupsMethod.delete: {
        const body = await this.delete(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VolumeBackupsMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VolumeBackupsMethod.runManually: {
        const body = await this.runManually(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case VolumeBackupsMethod.restoreVolumeBackupWithLogs: {
        const body = await this.restoreVolumeBackupWithLogs(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


