// Code generated by zapgen --target=ts; DO NOT EDIT.
// source: whitelabeling.zap

import {
  buildRequest,
  parseRequest,
  buildResponse,
  parseResponse,
  NO_TARGET,
  Status,
  type Call,
  type Response,
} from "@zap-proto/zap";

/** Method ordinals for the Whitelabeling service (stable wire ids). */
export const WhitelabelingMethod = {
  get: 1,
  update: 2,
  reset: 3,
  getPublic: 4,
} as const;

/** Typed RPC client for the Whitelabeling service over a ZAP call channel. */
export interface WhitelabelingChannel {
  /** Ship one Call envelope and await its correlated Response. */
  call(envelope: Uint8Array): Promise<Response>;
}

export class WhitelabelingClient {
  constructor(private readonly channel: WhitelabelingChannel, private readonly cap: Uint8Array = new Uint8Array(0)) {}

  async get(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: WhitelabelingMethod.get,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Whitelabeling.get: status ${resp.status}`);
    }
    return resp.body;
  }

  async update(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: WhitelabelingMethod.update,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Whitelabeling.update: status ${resp.status}`);
    }
    return resp.body;
  }

  async reset(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: WhitelabelingMethod.reset,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Whitelabeling.reset: status ${resp.status}`);
    }
    return resp.body;
  }

  async getPublic(args: Uint8Array): Promise<Uint8Array> {
    const envelope = buildRequest({
      method: WhitelabelingMethod.getPublic,
      promiseID: 0,
      target: NO_TARGET,
      cap: this.cap,
      payload: args,
    });
    const resp = await this.channel.call(envelope);
    if (resp.status !== Status.OK) {
      throw new Error(`Whitelabeling.getPublic: status ${resp.status}`);
    }
    return resp.body;
  }

}

/** Abstract RPC server for the Whitelabeling service. Subclass and implement each method. */
export abstract class WhitelabelingServer {
  abstract get(args: Uint8Array): Promise<Uint8Array>;
  abstract update(args: Uint8Array): Promise<Uint8Array>;
  abstract reset(args: Uint8Array): Promise<Uint8Array>;
  abstract getPublic(args: Uint8Array): Promise<Uint8Array>;

  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */
  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {
    const call: Call = parseRequest(envelope);
    switch (call.method) {
      case WhitelabelingMethod.get: {
        const body = await this.get(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case WhitelabelingMethod.update: {
        const body = await this.update(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case WhitelabelingMethod.reset: {
        const body = await this.reset(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      case WhitelabelingMethod.getPublic: {
        const body = await this.getPublic(call.payload);
        return buildResponse(Status.OK, call.promiseID, body);
      }
      default:
        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));
    }
  }
}


